### ISSUE TITLE
Can't find the details on how to run a particular deploy script file

### ISSUE THREAD

**Issue by chebykin** [wighawag/hardhat-deploy#102]
I'm getting started with this plugin but can't find a way to specify a particular migration file I want to run. Is there a way to do it?

**Comment by wighawag** [comment]
There is no direct way to execute one specific file

There are alternative though

You can add one specific tag to your deploy script and execute `hardhat deploy --tags <tag>`

see https://github.com/wighawag/hardhat-deploy#deploy-scripts-tags-and-dependencies

you can also have a folder that contains that only file and execute `hardhat deploy --deploy-scripts <folder>`

**Comment by chebykin** [comment]
Ok, thanks! I just never met the tag approach in migration patterns before so did not consider it as a solution.

Although it looks like double-work on naming both a file and a tag correctly, this tagging approach should be way more flexible 👍.
