### ISSUE TITLE
Conflict with @nomiclabs/hardhat-etherscan 2.1.2

### ISSUE THREAD

**Issue by tuler** [wighawag/hardhat-deploy#106]
```
node_modules/@nomiclabs/hardhat-etherscan/dist/src/type-extensions.d.ts:8:9 - error TS2687: All declarations of 'etherscan' must have identical modifiers.

8         etherscan: EtherscanConfig;
          ~~~~~~~~~

node_modules/hardhat-deploy/dist/src/type-extensions.d.ts:20:9 - error TS2717: Subsequent property declarations must have the same type.  Property 'etherscan' must be of type 'EtherscanConfig | undefined', but here has type '{ apiKey: string; } | undefined'.

20         etherscan?: {
           ~~~~~~~~~

  node_modules/@nomiclabs/hardhat-etherscan/dist/src/type-extensions.d.ts:5:9
    5         etherscan?: EtherscanConfig;
              ~~~~~~~~~
    'etherscan' was also declared here.

node_modules/hardhat-deploy/dist/src/type-extensions.d.ts:39:9 - error TS2687: All declarations of 'etherscan' must have identical modifiers.

39         etherscan?: {
           ~~~~~~~~~

node_modules/hardhat-deploy/dist/src/type-extensions.d.ts:39:9 - error TS2717: Subsequent property declarations must have the same type.  Property 'etherscan' must be of type 'EtherscanConfig', but here has type '{ apiKey: string; } | undefined'.

39         etherscan?: {
           ~~~~~~~~~

  node_modules/@nomiclabs/hardhat-etherscan/dist/src/type-extensions.d.ts:8:9
    8         etherscan: EtherscanConfig;
              ~~~~~~~~~
    'etherscan' was also declared here.


Found 4 errors.
```

**Comment by tuler** [comment]
https://github.com/wighawag/hardhat-deploy/commit/d3be773e3b81450e30954bc22997fc0b2ac86285#r50631518

**Comment by wighawag** [comment]
@tuler what command did you use to get that error ? Do you have a sample project.

I could not reproduce but I made a change in 0.7.7 that should fix it (use the same type now)

**Comment by tuler** [comment]
Hi @wighawag it's still failing for me.
I pushed a template repo we use for all solidity projects to https://github.com/cartesi/hardhat-template
It's not a minimal project, but it shows the error when you ran `yarn`.

**Comment by wighawag** [comment]
Thanks!
it was not the exact same type. pushed a new version in 0.7.9
Hopefully that should work for you too

**Comment by tuler** [comment]
It works now, thanks!

**Comment by tuler** [comment]
Is this issue back with `@nomiclabs/hardhat-etherscan@3.0.0` and `hardhat-deploy@0.9.24`?

**Comment by wighawag** [comment]
hmm, it might be due to https://github.com/wighawag/hardhat-deploy/pull/236
wondering I hardhat-deploy should have a different set of field names to avoid conflict

**Comment by tuler** [comment]
I think it's safer to use a different field for now.

There are other considerations about verification but that's a topic for another forum.

**Comment by clifton** [comment]
this is also happening to me

**Comment by zapaz** [comment]
> hmm, it might be due to #236 

Not sure, in hardhat-etherscan 3.0.0 `EtherscanConfig` type has changed according to this : 

https://github.com/nomiclabs/hardhat/tree/master/packages/hardhat-etherscan#multiple-api-keys-and-alternative-block-explorers

**Comment by zapaz** [comment]
> I think it's safer to use a different field for now.

good idea,  something like 'verify' , 'api' or 'scanapi'  ,  in order to keep these 2 different ways to get multichain verify

maybe it's also the occasion to add the api endpoint in config with the api key rather than in code ?
https://github.com/wighawag/hardhat-deploy/blob/master/src/etherscan.ts#L120-L186
