### ISSUE TITLE
Why deployerAddress is hardcoded in ensureCreate2DeployerReady 

### ISSUE THREAD

**Issue by Aniket965** [wighawag/hardhat-deploy#107]
> **Question -** deployerAddress is hardcoded in ensureCreate2DeployerReady  which is used while deploying using create2, why from is not used in it. 

https://github.com/wighawag/hardhat-deploy/blob/c977d223297a84b12f33a8f396c0152a9516ff69/src/helpers.ts#L271

**Comment by kautukkundan** [comment]
The `CREATE2` opcode works like this 
address = last 40 bytes of `keccak(0xff + msg.sender + salt + keccak(bytecode+args)` 

I don't understand the point of hardcoding the address of deployer contract as I was able to generate the correct address by setting msg.sender to another address.

Is it a hardhat specific thing? Can you explain a little more in detail? 

Actually me and @Aniket965 are working on a project where msg.sender is critical and keeps changing. We are able to get the correct addresses when deploying via contract using the CREATE2 assembly opcode. But we need to sync that off-chain.
