### ISSUE TITLE
Error: Command line params must be lowercase

### ISSUE THREAD

**Issue by heri16** [wighawag/hardhat-deploy#123]
How to reproduce:

```bash
npx hardhat node --forkDeployments mainnet --hostname 0.0.0.0 --watch
Error HH310: Invalid param --forkDeployments. Command line params must be lowercase.
```

Likely Cause:

https://github.com/nomiclabs/hardhat/blob/hardhat-core-v2.3.0/packages/hardhat-core/src/internal/cli/ArgumentsParser.ts#L26-L31

```typescript
  public static cLAToParamName(cLA: string): string {
    if (cLA.toLowerCase() !== cLA) {
      throw new HardhatError(ERRORS.ARGUMENTS.PARAM_NAME_INVALID_CASING, {
        param: cLA,
      });
    }
```

https://github.com/nomiclabs/hardhat/blame/767f68dee84d6a47cd40153a8ab8552f41a95d5e/packages/hardhat-core/src/internal/cli/ArgumentsParser.ts#L28

**Comment by heri16** [comment]
Looks like it is a README problem.

**Comment by wighawag** [comment]
Thanks, I updated the README
