### ISSUE TITLE
docs for companion network

### ISSUE THREAD

**Issue by tzapu** [wighawag/hardhat-deploy#125]
are there any docs anywhere about how to use a companion network?

can the companion network fork from an existing chain as well?

thank you for a wonderful plugin

/edit examples work as well :P

**Comment by wighawag** [comment]
thanks for the issue,
I added a section for companion networks : https://github.com/wighawag/hardhat-deploy#companionnetworks

**Comment by tzapu** [comment]
thank you very much 🙏
