### ISSUE TITLE
Verify only one specific contract

### ISSUE THREAD

**Issue by lcswillems** [wighawag/hardhat-deploy#126]
hardhat-deploy is such a great plugin!! It saved me so much time! Thanks a lot for the hard work!

I have a smart contract A that call a smart contract B.

I only want to publish the source of the smart contract A. How could I do it?

From the documentation, `etherscan-verify` seems to publish the source code for both.

**Comment by wighawag** [comment]
Hi @lcswillems thanks for the report
There is currently no way to do that, except to temporarly move the deployment file out of the deployment folder

I ll add that to the TODO list, we could have  --include --exclude option to `etherscan-verify` and `sourcify` tasks I suppose

I welcome a PR if you canot wait I implement it :)

**Comment by lcswillems** [comment]
I was thinking more about a programmable way to do it?

Currently, I have 2 files in `deploy` folder. One for contract A, one for contract B. In contract A, I would like to publish the sources and in contract B not do it.

Currently, there is a `deploy` function for deploying, maybe they could be a `verify` method?

**Comment by wighawag** [comment]
you can execute the `etherscan-verify` or `sourcify` task programmaticaly
but note that if you intend to call it as soon as the contract is deployed you might encounter error with etherscan or other as they might not have catch up with the chain yet

**Comment by lcswillems** [comment]
How could I call them programmaticaly? I looked at the source code of hardhat-deploy but note sure how to do it.

**Comment by wighawag** [comment]
This is part of hardhat. task can be called programmatically, please refers to their doc : https://hardhat.org/

**Comment by jamesmccomish** [comment]
Hello, I know some time has passed here, but I was also struggling to verify contracts in a nice way so [wrote this script](https://gist.github.com/jamesmccomish/f72f3c730c30b3ab97cedc668401ecc9) - open to feedback in case you find it useful, or if you have a better way!
