### ISSUE TITLE
Help with deployment

### ISSUE THREAD

**Issue by billtlee** [wighawag/hardhat-deploy#128]
Hi,

I am playing with hardhat-deploy but am having trouble getting my deployment to work.  I have attached the screenshot.  For some reason, it's complaining that it cannot find the artifacts for Token1, but the Token1.json is there.  Can someone point me in the right direction on what I might be doing wrong?  Thanks in advance!

<img width="1788" alt="Screen Shot 2021-06-17 at 11 57 58 AM" src="https://user-images.githubusercontent.com/14323281/122329108-664d8380-cf63-11eb-9bcc-c3e67f90097d.png">

**Comment by wighawag** [comment]
Could it be that there is multiple contract with the name Token1 ?
if so you ll need to specify the fully qualified name in the contract option :

```js
await deploy("Token1", {from: deployer, contract: "Token1.sol:Token1", args: [deployer], log: true)
```

**Comment by billtlee** [comment]
Good catch!  I had the same name for both the token contract.  Thx!

Now I modified by deployment to:

```
module.exports = async ({getNamedAccounts, deployments, network}) => {
  const {deploy} = deployments;
  const {deployer} = await getNamedAccounts();

  await deploy('UniswapV2Factory', {
    from: deployer,
    args: [deployer],
    log: true,
  });

  switch (network.name) {
    case 'mainnet':
      token1Address = '';
      token2Address = '';
      break;
    default:
      await deploy('Token1', {
        from: deployer,
        args: [],
        log: true,
      });
      await deploy('Token2', {
        from: deployer,
        args: [],
        log: true,
      });
  }
};
module.exports.tags = ['Factory'];
```

And now I am getting:

➜  core npx hardhat node
Nothing to compile
deploying "UniswapV2Factory" (tx: 0xec0bdbdc89a06160a173ffac18bfb489c5c335763fed0892bf6d8ac4f85408db)...: deployed at 0x5FbDB2315678afecb367f032d93F642f64180aa3 with 4139002 gas
deploying "Token1" (tx: 0xb2d891220861b122443274d185ee9de5132bd5aef7384f539a085f2c716aa722)...Error HH604: Error running JSON-RPC server: ERROR processing /Users/bill/Documents/MyProjects/ethereum-projects/Swap/UniswapFork/core/deploy/00_deploy_factory.js:
Error: ENOENT: no such file or directory, open '/Users/bill/Documents/MyProjects/ethereum-projects/Swap/UniswapFork/core/artifacts/build-info/62f5bb9a8dba70ffc081e2194817c2ca.json'

For more info go to https://hardhat.org/HH604 or run Hardhat with --show-stack-traces

Do you have any idea why?  Thx!

**Comment by wighawag** [comment]
Better create a new issue with link to code, cannot guess more with what you provide
I ll close this one

**Comment by billtlee** [comment]
Thanks!
