### ISSUE TITLE
Support Polygon Matic Mumbai testnet

### ISSUE THREAD

**Issue by heri16** [wighawag/hardhat-deploy#131]
https://github.com/wighawag/hardhat-deploy/blob/b8a0a05d2668cd52b3d932aac2387088491e0215/src/etherscan.ts#L146

Is there support for verifying contract on matic mumbai testnet?

**Comment by playsnook** [comment]
I think it's etherscan issue, not of hardhat deploy plugin: 
https://discord.com/channels/750408878008827925/750408878008827928/852627055782133771

**Comment by wighawag** [comment]
should be fixed in 0.8.10
