### ISSUE TITLE
Add `desiredConfirmations` option when executing transactions

### ISSUE THREAD

**Issue by lepidotteri** [wighawag/hardhat-deploy#134]
It would be useful for the hardhat-deploy execute function to support (maybe in the TxOptions field) an API for controlling how many confirmations should be waited for before returning the Receipt object response.
		
```
const rec: Receipt = await execute('BigContract', { from: deployer, desiredConfirmations: 2 }, 'transferOwnership', Timelock.address);
assert(rec.confirmations === 2);
```

**Comment by lepidotteri** [comment]
no updates @wighawag 🤕 ?

**Comment by wighawag** [comment]
Hey @lepidotteri sorry for the lack of reply, was in a 2 month break. I am back now, but catching up :)

I like the idea. I ll add this to the enhancement possible and see what I can do.

**Comment by wighawag** [comment]
This is now done, see https://github.com/wighawag/hardhat-deploy/pull/196
