### ISSUE TITLE
There should be a way to skip scripts based on the tags that they have

### ISSUE THREAD

**Issue by Dylan-Kerler** [wighawag/hardhat-deploy#139]
e.g. 

`deployFunc.tags = ["dev"]`

then you can skip this script like:

`npx hardhat deploy --skip-tags dev`

and any scripts with the tag "dev" will be skipped

**Comment by wighawag** [comment]
the tag system is a dependency system where tag can trigger more tag.
If we allow skip, not sure what the behaviour will be one tag that is not skipped need tag that is skipped.

I am closing the issue now but feel free to reopen with more info and the use case behind it

**Comment by burnto** [comment]
Thanks for creating this valuable project!

Just to add my experience here, I have a few deploy scripts that I use specifically for development and testing. For example, I have a script that stands up some fixtures to develop against. I've been using a `live` check and the presence of an environment variable to determine whether or not to skip these.

```ts
func.skip = async (hre: HardhatRuntimeEnvironment) => {
  return hre.network.live || !process.env.DEV_FIXTURES;
};
```

So then my invocation to start up my node with my fixtures looks like:

```bash
DEV_FIXTURES=1 npx hardhat node
```

This is basically fine, though I did spend some time trying to figure out how to skip unless a tag is specifically present.

**Comment by EdsonAlcala** [comment]
That's a great solution @burnto, I was exactly looking for this. My only concern is that I have many deploy scripts but I don't want to mix them with the production scripts, do you know if it is possible to have different folders with production and test deploy scripts? Thanks

**Comment by wighawag** [comment]
> That's a great solution @burnto, I was exactly looking for this. My only concern is that I have many deploy scripts but I don't want to mix them with the production scripts, do you know if it is possible to have different folders with production and test deploy scripts? Thanks

yes, you can setup deploy folders per network

```
...
networks: {
...
  mainnet: {
    url: ...
   deploy: ["deploy/001_example_1","deploy/001_example_2" ]
 },
   rinkeby: {
    url: ...
   deploy: ["deploy/001_example_1","deploy/001_example_2" , "deploy/only_on_rinkeby"]
 }
}
```

**Comment by EdsonAlcala** [comment]
that's awesome, thanks @wighawag

**Comment by EdsonAlcala** [comment]
oh wow I just notice you are from Scotland ! I'm from Edinburgh

**Comment by outdoteth** [comment]
Oh @EdsonAlcala did you previously work at Consensys on the staking team?! I see your commits on the internal codebase every day haha
