### ISSUE TITLE
Change the name of DefaultProxyAdmin to OpenZeppelinProxyAdmin

### ISSUE THREAD

**Issue by Dylan-Kerler** [wighawag/hardhat-deploy#140]
`DefaultProxyAdmin` is the same as the `ProxyAdmin` in OpenZeppelin. To be consistent with the naming of `OpenZeppelinTransparentProxy` the admin contract should be named `OpenZeppelinProxyAdmin` instead of `DefaultProxyAdmin`.

Otherwise the implication is that `DefaultProxyAdmin` is a custom admin contract unique to hardhat-deploy.

**Comment by wighawag** [comment]
It is actually a slightly different implementation than openzeppelin one. it allow you to set the owner in the constructor, something openzeppelin implementation do not allow (it hardcode msg.sender)
