### ISSUE TITLE
Question about multiple deploy folder specific to each network.

### ISSUE THREAD

**Issue by playsnook** [wighawag/hardhat-deploy#144]
According [to](https://hardhat.org/plugins/hardhat-deploy.html#hardhat-deploy-in-a-nutshell)

_Furthermore hardhat-deploy can also support a multi-chain settings like L1, L2 with multiple deploy folder specific to each network._

Can you please provide an example of how to use it?

Currently, I have 20 deploy scripts which should deploy only to L2 and 2 scripts which deploy only to L1.

The solution I use is in the following example:

For L1 scripts:

```js
const { network } = require('hardhat');
module.exports = async ({
  // code
};
module.exports.skip = async () => network.name !== 'goerli';
```

For L2 scripts:

```js
const { network } = require('hardhat');
module.exports = async ({
  // code
};
module.exports.skip = async () => network.name !== 'mumbai';
```

That works but I need to place `const { network } = require('hardhat');` and `module.exports.skip = async () => network.name !== 'mumbai';` in every of my 20 scripts. 
Is there some better way, for example specifying a deployment folder which is specific for L1 or L2?

Thanks

**Comment by wighawag** [comment]
You can use the deploy field of the network objects in hardhat.config. like https://github.com/wighawag/template-ethereum-contracts/blob/b9365c445add722313e25826ba2133c535dd1c53/hardhat.config.ts#L74
