### ISSUE TITLE
Question on testing upgradable contracts

### ISSUE THREAD

**Issue by playsnook** [wighawag/hardhat-deploy#145]
OZ shows the way of usage of their plugins in [tests](https://docs.openzeppelin.com/upgrades-plugins/1.x/):

```js
it('works before and after upgrading', async function () {
  const instance = await upgrades.deployProxy(Box, [42]);
  assert.strictEqual(await instance.retrieve(), 42);

  await upgrades.upgradeProxy(instance.address, BoxV2);
  assert.strictEqual(await instance.retrieve(), 42);
});
```

Can you please advice on how to test upgrdable contracts with hardhat-deploy plugin?
Thanks

**Comment by wighawag** [comment]
You can execute the deploy function with different implementation each time

but with hardhat-deploy deploy scripts you can actually even do better using tags and `upgradeIndex`. I need to write some doc on it though.
