### ISSUE TITLE
Multiple deployments of the *same* contract

### ISSUE THREAD

**Issue by pandichef** [wighawag/hardhat-deploy#148]
I have a project where I need to deploy the same smart contract twice, passing in different constructor parameters to each deployment e.g.,
001_deploy_mycontract_param_abc.ts
002_deploy_mycontract_param_xyz.ts

But in deployments/, I see just one json file output (mycontract.json) corresponding to the 2nd deployment.  The first deployment of that contract appears nowhere.  Is this the expected behavior?  

If so, what's the right way to achieve the desired result?

**Comment by jtlacci** [comment]
what was the resolution for this?
