### ISSUE TITLE
--fork-deployments removed without proper documentation

### ISSUE THREAD

**Issue by heri16** [wighawag/hardhat-deploy#155]
What is the replacement for:
```
npx hardhat node --hostname 0.0.0.0 --fork-deployments mumbai --as-network localhost --watch"
```

I don't quite understand this commit. to get it working again: 

https://github.com/wighawag/hardhat-deploy/commit/8f1fbab9a39f2bcc8c64dc3943137c46f81743bc

**Comment by heri16** [comment]
@wighawag Any help?

**Comment by heri16** [comment]
There is also a change in behaviour.

Previously when `npx hardhat node` with config:

```typescript
hardhat: {
      tags: ['test', 'local'],
      chainId: 80001,
      forking: {
        url: `https://speedy-nodes-nyc.moralis.io/${SPEEDY_NODES_API_KEY}/polygon/mumbai/archive`,
        blockNumber: 16260000, // See: https://mumbai.polygonscan.com/block/16260000
      },
    },
    localhost: {
      tags: ['local'],
    },
```

`hre.network.tags.local` will be set in deploy scripts.

The new behaviour is that it will not be set.

**Comment by wighawag** [comment]
Hi @heri16 thanks for the report, the reason for the change was that it was hard to maintain the previous mechanism and that modifying the network name raised potential issue with other plugins. The proper solution should be handled in hardhat in my opinion, see https://github.com/nomiclabs/hardhat/issues/1164

Re tags, I ll see what I can do, maybe I need to reinstantiate the equivalent of the previous cmd options

**Comment by wighawag** [comment]
Closing this and I created a new issue for the tags issue here : https://github.com/wighawag/hardhat-deploy/issues/202
