### ISSUE TITLE
Multiple tags not working

### ISSUE THREAD

**Issue by suranap** [wighawag/hardhat-deploy#157]
- `hardhat node --tags A` works
- `hardhat node --tags A, B` fails this this message: 
  ```
  $ yarn hardhat node --tags A, B
  Error HH308: Unrecognized positional argument B
  ```
- `hardhat node --tags "A, B"` only executes A, ignores B

The help text says: "specify which deploy script to execute via tags, separated by commas". What's the right way to pass in multiple tags?

**Comment by wighawag** [comment]
Hi, do not add space after the commas
