### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by drortirosh** [wighawag/hardhat-deploy#161]
Some in-page links in the documentation page are broken **when viewed on the hardhat doc** site, 
e.g. : https://hardhat.org/plugins/hardhat-deploy.html#1-hardhat-deploy

(strangely, they are completely valid while viewed in the github README.md file - but I believe many users are viewing it as the "official" deployer of hardhat)

**Comment by aspiers** [comment]
I see this too.  Since this is an issue with hardhat.org rather than with this plugin, I submitted https://github.com/nomiclabs/hardhat/issues/1800 to track it there.

**Comment by wighawag** [comment]
Closing this as this is not an hardhat-deploy issue
