### ISSUE TITLE
Deployment don't work.

### ISSUE THREAD

**Issue by Gauddel** [wighawag/hardhat-deploy#166]
hardhat-deploy version: 0.8.11

I am trying to deploy a simple contract with one dependency called ProtectionResolver.sol

![image](https://user-images.githubusercontent.com/12876892/127618158-e4dea15f-6986-4fa2-bbb7-59f571ce354c.png)

I get stuck, no error and no deployment.

![image](https://user-images.githubusercontent.com/12876892/127617731-f667d2d5-be94-4c8a-a0b4-5441f067b363.png)

Let me know if you need more information.

Thanks!

**Comment by wighawag** [comment]
This is most likely due to gas change while the deploy tx was sent, you can safely restart the process.
new version of hardhat-deploy will ask you if you want to increase gas
older will keep waiting for the tx unless you delete the .pendingTransactions file in the deployment folder
