### ISSUE TITLE
--export should create the path if it doesn't exist

### ISSUE THREAD

**Issue by kyriediculous** [wighawag/hardhat-deploy#171]
I'm trying to save my deployments with `--write false` , this doesn't create the deployments directory. 

However I want to just have single file exports using e.g. `--export deployments/contracts.json` but this fails with `--write false` if the target directory for the file doesn't exist. 

**expectations**
Create the missing directories if they do not exist

**Comment by wighawag** [comment]
fixed in 0.9.22
