### ISSUE TITLE
hre.network.tags is undefined for the "hardhat" network.

### ISSUE THREAD

**Issue by adjisb** [wighawag/hardhat-deploy#176]
For the hardhat network the hre.network.tags is missing, it seems to be populated in createNetworkFromConfig but the function call is explicitly skipped for the "hardhat" network in index.ts:254.

**Comment by wighawag** [comment]
can you describe in more details your issue.

line 254 only deal with the storage of extra network, used in companion network, the tags should not be affected

**Comment by adjisb** [comment]
It seems that the call to createNetworkFromConfig is skipped for the hardhat network:
```for (const networkName of Object.keys(env.config.networks)) {
      const config = env.config.networks[networkName];
      if (!('url' in config) || networkName === 'hardhat') {
        continue;
      }
      store.networks[networkName] = createNetworkFromConfig(
        env,
        networkName,
        config
      );
    }
```

Create network config seems to be the code that adds the tags field to the configuration:
```
function createNetworkFromConfig(
  env: HardhatRuntimeEnvironment,
  networkName: string,
  config: NetworkConfig
): Network {
  const tags: {[tag: string]: boolean} = {};
  const tagsCollected = config.tags || [];
  for (const tag of tagsCollected) {
    tags[tag] = true;
  }

  const network = {
    name: networkName,
    config,
    live: config.live,
    saveDeployments: config.saveDeployments,
    tags,
    deploy: config.deploy || env.config.paths.deploy,
    companionNetworks: {},
  };
```

I'm trying to access the value of `hre.network.tags` during a deploy and I get undefined.

**Comment by wighawag** [comment]
this function is only for extra network (used by the companion feature)

for the current network has its tags set here : https://github.com/wighawag/hardhat-deploy/blob/f96f725a9f5ac46493a7cc18e95f1fb6258f48c2/src/index.ts#L237

so maybe your issue is elswhere. if you have a repo where you reproduce the issue I could have a look

**Comment by adjisb** [comment]
Probably I'm wrong then.
It happens when I run solidity-coverage.

**Comment by wighawag** [comment]
Ha, that explains it then, solidity-coverage has a bug that make it remove all associated information, 
see : https://github.com/sc-forks/solidity-coverage/issues/624
and : https://github.com/wighawag/hardhat-deploy/issues/132
