### ISSUE TITLE
A contract is redeployed even when no changes were made to it

### ISSUE THREAD

**Issue by playsnook** [wighawag/hardhat-deploy#179]
I change one contract of many by adding a function and run deploy. For some reason, one of non-changed contracts is redeployed, too, along with the changed contract.

Here is the comparison of diff between commit without the change and with the change after deploy:

https://i.imgur.com/f0k8u8d.png

We can see that only SnookGame.sol is changes, but StakingRewards was redeployed too.

Can you explain this behavior?

**Comment by wighawag** [comment]
could it be that StakingReward import SnookGame ?
hardhat-deploy basically check if the deploy's tx.data from previous deployment equal the new tx.data and if they differs, it deploy the new version

**Comment by playsnook** [comment]
Yes, I accidently imported SnookGame which is not used. Thanks alot for the explanation.

I think it would be useful if you put this comment `hardhat-deploy basically check if the deploy's tx.data from previous deployment equal the new tx.data and if they differs, it deploy the new version` somewhere in the documentation, for example, in the topic on upgrades.
