### ISSUE TITLE
etherscan-verify needs updating

### ISSUE THREAD

**Issue by rhlsthrm** [wighawag/hardhat-deploy#184]
Arbitrum is not verifying on Etherscan and the team said we need `hardhat-etherscan v2.1.6` or later. Can it be updated in this package?

**Comment by wighawag** [comment]
hardhat-deploy do not use `hardhat-etherscan` it implements the submission to etherscan itself

**Comment by rhlsthrm** [comment]
Ah okay I was wondering why I couldn't find it in the sources. In that case, the mechanism needs to be updated to support Arbitrum.
