### ISSUE TITLE
Multiple deployments of the *same* contract (duplicate)

### ISSUE THREAD

**Issue by jtlacci** [wighawag/hardhat-deploy#185]
This is a duplicate as the original was closed without resolution. 

ref: https://github.com/wighawag/hardhat-deploy/issues/148

I have a project where I need to deploy the same smart contract twice, passing in different constructor parameters to each deployment e.g.,
001_deploy_mycontract_param_abc.ts
002_deploy_mycontract_param_xyz.ts

But in deployments/, I see just one json file output (mycontract.json) corresponding to the 2nd deployment. The first deployment of that contract appears nowhere. Is this the expected behavior?

If so, what's the right way to achieve the desired result?

**Comment by wighawag** [comment]
```
await deploy("MyContract_1", {from: deployer, contract: "ContractArtifactName"});
await deploy("MyContract_2", {from: deployer, contract: "ContractArtifactName"});
```

the first name is not the name of the artifact but the name of the deployment. it no artifact is provided (`contract` field) it will find the artifact with the same name
