### ISSUE TITLE
Make DeployFunction.dependencies (env: HardhatRuntimeEnvironment) => Promise<string[]> 

### ISSUE THREAD

**Issue by YoannXdev** [wighawag/hardhat-deploy#191]
Like in the `skip `properties of the `DeployFunction`, I would like to have the HardhatRuntimeEnvironment in `dependencies `properties. 

We have a "common" contract which is the same in L1 and L2 the only difference is the dependencies, eg it's name Sand on L1 and PolygonSand on L2. I would like to have the ability to check whether I'm on L1 or L2 in the dependencies and returning either ['SAND'] or ['PolygonSand'] according to the context.

**Comment by wighawag** [comment]
The dependency tree is currently build synchronously ahead of time and changing that might not be simple.
Bit for your use case, could you not simply name PolygonSand: SAND ?

**Comment by YoannXdev** [comment]
Ok, you mean renaming and using the companion network right? Otherwise, how the HHDeploy knows which contract you want when you fetch SAND (the L1 or L2 one)?

**Comment by wighawag** [comment]
companion network are just so that you can deploy all of it in one go, even they are from different network

There can only be one SAND per network, HHDeploy will just pick the one saved in the corresponding deployment folder. if you execute deploy on L1 it will pick SAND from L1, and same for L2
