### ISSUE TITLE
support for custom factory

### ISSUE THREAD

**Issue by tzapu** [wighawag/hardhat-deploy#192]
hi, hardhat-deploy rocks, thank you !

i wanted to check if there is a possibility for me to use the cool deployment bits of hardhat-deploy with a custom factory.

i have a factory for deploying contracts on which i call deploy with the necessary args, is there anyway i could use that in deployments so they recognized as such and i can use all the nifty hardhat-deploy functionality with them? Maybe run a script in a deployment that does the .deploy() calling and then creates the deployment programmatically?

factory can be seen here: https://github.com/BarnBridge/SmartAlpha/blob/main/contracts/PoolFactory.sol

thanks

**Comment by wighawag** [comment]
Hi @tzapu it is indeed possible to use factories but you need to go through extra call

The way I do it is that I deploy my contract via a factory that emit an event about the new contract address

I fetch that adress from the event and call `deployments.save` with the info I want to keep, see the type for deployment object expected by `deployments.save` : https://github.com/wighawag/hardhat-deploy/blob/59633283034c57a2038537f0034c74bd5c871b89/types.ts#L211
The only one requires are address and abi

hope that helps

**Comment by tzapu** [comment]
hey @wighawag this worked perfectly.
is there anychance i could get metadata from somewhere as well? to save it with the deployment and have access to verify after as well?

**Comment by wighawag** [comment]
Hi @tzapu yes you can use `deployments.getExtendedArtifact` which will return you that type : https://github.com/wighawag/hardhat-deploy/blob/59633283034c57a2038537f0034c74bd5c871b89/types.ts#L11

**Comment by tzapu** [comment]
yeah, just found that, that s amazing, works splendidly. THANK YOU!
