### ISSUE TITLE
readme is very complex

### ISSUE THREAD

**Issue by AhmadBan** [wighawag/hardhat-deploy#193]
Hi,
I just wanted to start using this library but I could not find any example that shows how to use it. I found and example but nowhere is something of how to use this example what is the proper command to use it and also overall the readme file is too complex to be understood by a new user to hardhat

Thanks

**Comment by wighawag** [comment]
Hi @AhmadBan thanks for the feedback.
I welcome any suggestion to improve the README. Some examples are mentioned into it, see https://github.com/wighawag/template-ethereum-contracts

There is also a tutorial (that might not be fully up to date) mentioned in this section: https://github.com/wighawag/hardhat-deploy/#hardhat-deploy-in-a-nutshell

tutorial : https://github.com/wighawag/tutorial-hardhat-deploy

Hope that helps
