### ISSUE TITLE
The deterministic function doesn't return proxy's address

### ISSUE THREAD

**Issue by marcelomorgado** [wighawag/hardhat-deploy#199]
When using the `deterministic` function to discover the address of an upgradable contract, it's returning the implementation address only.

See more: https://github.com/wighawag/hardhat-deploy/issues/129#issuecomment-929381609

Maybe would be useful to return both? For instance `const { address, implementation, deploy } = deterministic(...)` where `address` and `implementation` are the same when isn't using proxy.

**Comment by wighawag** [comment]
fixed in 0.9.3 but let me know if hit any issues
Thanks for the report!
