### ISSUE TITLE
Deploy script sometimes not executing contract calls

### ISSUE THREAD

**Issue by suranap** [wighawag/hardhat-deploy#200]
Here's a simplified snippet from my deploy script. The `deploy` call executes just fine. When I deploy to hardhat and testnets, the call to OpenZepplin's AccessControl `grantRole` executes every time. When I deploy to mainnet, it worked 2 times and did not execute 2 times. There's no output to the console with extra info. I then execute the same call manually and it works. 

Any idea what could be causing this? 

```
import {HardhatRuntimeEnvironment} from 'hardhat/types';
import { DeployFunction } from "hardhat-deploy/types";
import { ethers } from "hardhat";
import { getAddress, keccak256 } from "../scripts/utils/helpers";

const deployMyContract: DeployFunction = async (hre: HardhatRuntimeEnvironment) => {
  const { deployments, getNamedAccounts } = hre;
  const { deploy } = deployments;
  const { deployer } = await getNamedAccounts();
  const address = getAddress(hre);
  const helper = await ethers.getContract("SupportingContract");

  await deploy("MyContract", {
    from: deployer,
    args: [
      helper.address,
    ],
    log: true,
  });
  const myContract = await ethers.getContract("MyContract");

  // This contract call sometimes not executed when deploying to mainnet
  await helper.grantRole(
    keccak256(Buffer.from("DEFAULT_ADMIN_ROLE", "utf-8")),
    myContract.address
  );
};

export default deployMyContract;
deployMyContract.tags = ["MyContract"];
```

**Comment by wighawag** [comment]
What is `await registry.grantRole(` ?

in particular what is `registry` ?

it looks like an ethers Contract instance, in which case you might want to wait for the tx to be mined via

```
const tx = await registry.grantRole...
await tx.wait();
```

**Comment by suranap** [comment]
> What is `await registry.grantRole(` ?

Sorry, I simplified the code snippet but forgot to rename `registry` to `helper`. Yes, it's an ethers Contract instance. I'll add an explicit wait on those calls.
