### ISSUE TITLE
Add support for etherscan-verify on new avalanche snowtrace

### ISSUE THREAD

**Issue by UrsaMaritimus** [wighawag/hardhat-deploy#217]
It was announced today that a version of etherscan is now launching on Avalanche. It would be very helpful for verification if ethercan-verify supported this and the testnet.

Avalanche C-Chain: 43114, https://snowtrace.io/
Avalanch Fuji: 43113: https://testnet.snowtrace.io/

**Comment by mastyf** [comment]
merged here https://github.com/wighawag/hardhat-deploy/pull/218 and here https://github.com/wighawag/hardhat-deploy/pull/226
