### ISSUE TITLE
deployment tags and tests - fixtures seem to run all deployments even when specific ones set.

### ISSUE THREAD

**Issue by null-prophet** [wighawag/hardhat-deploy#219]
Hi again,

I'm working on a project and I have 2 contracts
```
ContractOneNFT.sol
ContractTwoStore.sol
```

And I have 3 deploy scripts:

```
001_deploy_ContractOneNFT.ts
002_deploy_ContractTwoStore.ts
003_configure_ContractTwoStore.ts
```

So in `001_deploy_ContractOneNFT.ts`
```
// ... rest of setup
export default func;
func.id = 'ContractOneNFT';
func.tags = ['ContractOneNFT'];
```

So in `002_deploy_ContractTwoStore.ts`
```
// ... rest of setup
export default func;
func.id = 'ContractTwoStore';
func.tags = ['ContractTwoStore'];
func.dependencies = ['ContractOneNFT'];
```

So in `003_configure_ContractTwoStore.ts`
```
// ... rest of setup
export default func;
func.id = 'ConfigureStore';
func.tags = ['ConfigureStore'];
func.dependencies = ['ContractTwoStore'];
```

So I think those dependencies are ok, the configure depends on the store and the store depends on the NFT contract.

In my tests I have setup the fixtures to only call the store, not the setup. As I want to test the setup in the tests. But the setup is run every time and the tests fail now.

`StoreTest.test.ts`
```
const setup = deployments.createFixture(async () => {
  // fixme
  await deployments.fixture('ContractTwoStore');

  const {deployer, minter, player1, player2} = await getNamedAccounts();
....
```

What am I doing wrong here? Sorry if this is a dumb question but I followed the rules in the docs around the naming and using tags but I've probably done something daft in the the config. All the tasks for running tests etc are standard from the sample project you give as a template.

**Comment by wighawag** [comment]
If you use the template, it by default set an environment variable that run all script before the tests are run

this is to speed up the tests because like this the deploy script need to be run only once for the all test suite.

see `HARDHAT_DEPLOY_FIXTURE=true` in https://github.com/wighawag/template-ethereum-contracts/blob/e14740c542711561c20f3872421f1a0cd7f2caab/package.json#L60

if you do not want that you can remove that variable

**Comment by null-prophet** [comment]
Ah, ok, that makes total sense now.

I will remove the flag and give it a shot. Thanks so much for the speedy reply again!

maybe worth nothing that somewhere in the docs around testing/tags?

**Comment by wighawag** [comment]
Yes, you right, documentation is not great currently, need to improve and for the tempate, should put a note somewhere. I ll leave that issue open until I do. thanks for the report!
