### ISSUE TITLE
Unhandled Etherscan error 'Contract already verified'

### ISSUE THREAD

**Issue by wei3erHase** [wighawag/hardhat-deploy#220]
When deploying 2 times exactly the same contract (with same arguments), at the moment of verifying the second contract in Etherscan, it will revert with a 'Contract already verified' error (since Etherscan had found a Similar Match Source Code). 

The command used to verify is `hre.run('verify:verify',{...})`

This interrupts the deployment scripts, even though the result is the same as having verified the contract source.

**Comment by wighawag** [comment]
I would advise against verify contract as part of the deploy script, as this is not guaranteed to work.
You could always try catch. let me know if this is not good enough
