### ISSUE TITLE
Allow to specifc fallback Etherscan url

### ISSUE THREAD

**Issue by rmeissner** [wighawag/hardhat-deploy#225]
To keep up with new Etherscan instances that pop up it would be nice if it is possible to specify the Etherescan api endpoint via the config.

**Comment by wighawag** [comment]
Yes! I think about that about it every time I merge a etherscan url PR :)

**Comment by wighawag** [comment]
included in 0.10.0 (breaking change: now hardhat-deploy use the `verify` field in hardhat.config

see : https://github.com/wighawag/hardhat-deploy#4-hardhat-etherscan-verify
