### ISSUE TITLE
Module '"hardhat"' has no exported member 'deployments'

### ISSUE THREAD

**Issue by PatrickAlphaC** [wighawag/hardhat-deploy#228]
I have the following code

```javascript
import { deployments } from "hardhat"
```

In my typescript file. How do we make this linting error go away? It looks like it's because it's a [side effect](https://codesource.io/avoiding-side-effects-in-javascript-code/).

<img width="637" alt="Screen Shot 2021-11-17 at 1 22 30 PM" src="https://user-images.githubusercontent.com/54278053/142259719-1fc921ba-a283-45ec-af6b-3ef1539956ac.png">

Any thoughts?

**Comment by wighawag** [comment]
I don't think it is linked to side effect, hardhat-deploy do not add anything to the global scope. Hardhat does but your error is probably related to something else. Do you have a repo exemplifying the issue?

**Comment by PatrickAlphaC** [comment]
Well now I feel silly... I can't reproduce it...

It's happened a few times to me... so I'll stay vigilant to what my setup is next time.

**Comment by PatrickAlphaC** [comment]
In case anyone else runs into this, I found out what was going on. In your `tsconfig.json` you need to add all scripts in the `include` section, otherwise typescript will get confused.

**Comment by aalmada** [comment]
I had this working fine for a long time but recently changed the `tsconfig.ts` to use [project references](https://www.typescriptlang.org/docs/handbook/project-references.html) and this same issue started.
I already tried to use `"include": ["./**/*.ts"]` or to list each folder but none solved the issue.
Is there any other tip to solve this issue?

**Comment by aalmada** [comment]
I'm using `deployments` to create fixtures. So, I went back and reread the documentation on it.
I found that if I use `const {deployments} = require('hardhat');` everything works fine. 
If I convert it to `import {deployments} from 'hardhat';` then I get the error `error TS2305: Module '"hardhat"' has no exported member 'deployments'.`.
I'm using typescript.

**Comment by dcsan** [comment]
I found I had skipped a couple of stages with other modules and hardhat config

https://docs.openzeppelin.com/upgrades-plugins/1.x/hardhat-upgrades

**Comment by rangershi** [comment]
> I found that if I use `const {deployments} = require('hardhat');` everything works fine. If I convert that to `import {deployments} from 'hardhat';` then I get the error `error TS2305: Module '"hardhat"' has no exported member 'deployments'.`. I'm using typescript.

I hited the same problem, even if i use `const {deployments} = require('hardhat');` ,it will report :" Cannot read properties of undefined (reading 'fixture')" when I "  await deployments.fixture([fix_name]);"  

what the matter?

**Comment by dandamian83** [comment]
hey, had the same problem, 
![image](https://user-images.githubusercontent.com/12101673/194022036-8deafa8f-11af-4dc4-980c-70f9e6adef85.png)
I've fixed it by including in the hardhat.config.ts the following imports:
``import "@nomiclabs/hardhat-waffle";
import "hardhat-deploy";``
