### ISSUE TITLE
Consider removing the `--show-accounts` flag?

### ISSUE THREAD

**Issue by fvictorio** [wighawag/hardhat-deploy#234]
The latest versions of Hardhat are a bit smarter about the accounts being shown. Now we only show the private keys of the configured accounts if the default mnemonic is used, but we hide them if not.

Assuming that the idea of hiding the accounts by default was to protect user's private keys (which makes a lot of sense!), would you consider removing that behavior now that Hardhat does the right thing?

The reason to ask for this is that users get confused by the lack of output now and then, since they don't realize that `hardhat-deploy` is adding that behavior, which conflicts with what our docs show.

**Comment by wighawag** [comment]
Done, by increasing the peer dependency of hardhat to 2.6.8 in hardhat-deploy 0.9.21

**Comment by fvictorio** [comment]
Thank you!
