### ISSUE TITLE
How to get deployed contract

### ISSUE THREAD

**Issue by shunkakinoki** [wighawag/hardhat-deploy#239]
https://github.com/ethereum-optimism/contracts/blob/df10de974629615b8597ed9bdbcd1b5ec2c0c9b7/src/hardhat-deploy-ethers.ts#L80

**Comment by shunkakinoki** [comment]
Is there any function build in like the above?

**Comment by shunkakinoki** [comment]
Would be nice if we could write and invoke functions directly from the deploy script

**Comment by akshatcx** [comment]
you can use `await hre.deployments.get("ContractName");` where `hre` is the `HardhatRuntimeEnvironment` to get the deployed contract object
