### ISSUE TITLE
Specifying a private key in from field results in 'invalid object key - maxFeePerGas'

### ISSUE THREAD

**Issue by starlabs007** [wighawag/hardhat-deploy#240]
I'm setting the `from` field with a private key during a call to `deploy(...)`:
```ts
  await deploy('ContractFoo', {
    from: deployerSigner.privateKey,
    args: [],
    log: true,
  });
```

I'm getting this error - it's from ethers.js.
```
  reason: 'invalid object key - maxFeePerGas',
  code: 'INVALID_ARGUMENT',
  argument: 'transaction:maxFeePerGas',
```

From the error callstack, what's getting passed to ethers.js is the following (I cropped out the data field):
```ts
 value: {
    gasLimit: 919749,
    gasPrice: BigNumber { _hex: '0x02540be400', _isBigNumber: true },
    maxFeePerGas: undefined,
    maxPriorityFeePerGas: undefined,
    value: undefined,
    nonce: 152,
    data: '....',
    type: 0,
    chainId: 97
  }
}
```
Looking at the ethers.js code, if the txn is a legacy one then it [checks for valid keys](https://github.com/ethers-io/ethers.js/blob/71b7547f10229f50d8b701611c5e6041b8ed966b/packages/transactions/src.ts/index.ts#L106) and just the existence of `maxFeePerGas` and `maxPriorityFeePerGas` keys are causing this exception, even though their values are undefined.

I'm not encountering this on the hardhat network but when deploying to a live one (BSC in this case). Is there a way to workaround this or have hardhat-deploy not set those keys?

**Comment by wighawag** [comment]
should be fixed in 0.9.16
