### ISSUE TITLE
How to deploy contract with UUPSUpgradeable ?

### ISSUE THREAD

**Issue by Vorh** [wighawag/hardhat-deploy#242]
Hello! 
I try to use `hardhat-deploy` with OpenZeppelin UUPS contracts and get error:
` function "upgradeTo" will shadow "upgradeTo". Please update code to avoid conflict.`
I read the previous issues #146 and #213 , but did not understood how to solve the problem.

What do I need to do so that the contract can be deployed using plugin? :(

Token contract:

```
contract UsdPlusToken is Initializable, ERC20Upgradeable, AccessControlUpgradeable, UUPSUpgradeable {
    bytes32 public constant EXCHANGER = keccak256("EXCHANGER");
    bytes32 public constant UPGRADER_ROLE = keccak256("UPGRADER_ROLE");

    uint256 public liquidityIndex;
    uint256 public liquidityIndexDenominator;

   modifier onlyAdmin() {
        require(hasRole(DEFAULT_ADMIN_ROLE, msg.sender), "Restricted to admins");
        _;
    }

    modifier onlyExchanger() {
        require(hasRole(EXCHANGER, msg.sender), "Caller is not the EXCHANGER");
        _;
    }

 /// @custom:oz-upgrades-unsafe-allow constructor
    constructor() initializer {}

    function initialize() initializer public {
        __ERC20_init("USD+", "USD+");
        __AccessControl_init();
        __UUPSUpgradeable_init();

        _grantRole(DEFAULT_ADMIN_ROLE, msg.sender);
        _grantRole(UPGRADER_ROLE, msg.sender);

        liquidityIndex  = 10 ** 27; // as Ray
        liquidityIndexDenominator = 10 ** 27; // Ray
    }

    function _authorizeUpgrade(address newImplementation)
    internal
    onlyRole(UPGRADER_ROLE)
    override
    {}

}

```

Deploy script:

```
   await deploy('UsdPlusToken', {
        from: deployer,
        args: [],
        log: true,
        proxy: {
            owner: deployer,
            proxyContract: "UUPSUpgradeable",
        },
    });

```

**Comment by Vorh** [comment]
@wighawag Hey! Forgive me please for bothering you with such questions  :(

I found another solution, but don't know is it correct: 

1) Deploy proxy by OpenZeppelin plugin
2) Save to deployments by your plugin

``` 
const {ethers, upgrades} = require("hardhat");
module.exports = async ({getNamedAccounts, deployments}) => {
    const {deploy, save} = deployments;
    const {deployer} = await getNamedAccounts();

    const UsdPlusToken = await ethers.getContractFactory('UsdPlusToken');
    const proxy = await upgrades.deployProxy(UsdPlusToken, {kind: 'uups'});
    console.log('Deploy UsdPlusToken Proxy done -> ' + proxy.address);

    const impl = await upgrades.upgradeProxy(proxy, UsdPlusToken);
    console.log('Deploy UsdPlusToken Impl  done -> ' + impl.address);

    const artifact = await deployments.getExtendedArtifact('UsdPlusToken');
    let proxyDeployments = {
        address: proxy.address,
        ...artifact
    }

    await save('UsdPlusToken', proxyDeployments);
};

module.exports.tags = ['base', 'UsdPlusToken'];
```

**Comment by wighawag** [comment]
Yes, this solution is perfectily fine. save and get is really the core of hardhat-deploy

My plan is still to support UUPS natively, but not sure yet when

**Comment by n00b21337** [comment]
> @wighawag Hey! Forgive me please for bothering you with such questions :(
> 
> I found another solution, but don't know is it correct:
> 
> 1. Deploy proxy by OpenZeppelin plugin
> 2. Save to deployments by your plugin
> 
> ```
> const {ethers, upgrades} = require("hardhat");
> module.exports = async ({getNamedAccounts, deployments}) => {
>     const {deploy, save} = deployments;
>     const {deployer} = await getNamedAccounts();
> 
>     const UsdPlusToken = await ethers.getContractFactory('UsdPlusToken');
>     const proxy = await upgrades.deployProxy(UsdPlusToken, {kind: 'uups'});
>     console.log('Deploy UsdPlusToken Proxy done -> ' + proxy.address);
> 
>     const impl = await upgrades.upgradeProxy(proxy, UsdPlusToken);
>     console.log('Deploy UsdPlusToken Impl  done -> ' + impl.address);
> 
>     const artifact = await deployments.getExtendedArtifact('UsdPlusToken');
>     let proxyDeployments = {
>         address: proxy.address,
>         ...artifact
>     }
> 
>     await save('UsdPlusToken', proxyDeployments);
> };
> 
> module.exports.tags = ['base', 'UsdPlusToken'];
> ```

this is great, really helpful to plug in  UUPS into HH deploy.

**Comment by n00b21337** [comment]
> Yes, this solution is perfectily fine. save and get is really the core of hardhat-deploy
> 
> My plan is still to support UUPS natively, but not sure yet when

@wighawag  so I dont open new issue, Wondering what is recommended way to upgrade UUPS SC now? Do we use regulat hardhat upgrade pattern like below and mentioned above
```
  const BoxV2 = await ethers.getContractFactory("BoxV2");
  const upgraded = await upgrades.upgradeProxy(instance.address, BoxV2);
```

or is there some way to do that with "deploy" method and using "upgradeTo"  method?
