### ISSUE TITLE
add progress info

### ISSUE THREAD

**Issue by drortirosh** [wighawag/hardhat-deploy#243]
it would be great to add a `--progress` cmdline to show what is getting deployed (or reused)

I use the following deploy wrapper function:

```js
  async function deploy (name: string, options: DeployOptions): Promise<DeployResult> {
    console.log('Deploying: ', name)
    const res = await hre.deployments.deploy(name, options)
    console.log(name, res.address, res.newlyDeployed === true ? 'newlyDeployed' : '(not modified)')
    return res
  }
```

**Comment by wighawag** [comment]
you can set the log option to true for that

like

`deploy({from: deployer, log: true}...)`

**Comment by drortirosh** [comment]
thanks. just found that (missed it in the readme..)
still, it doesn't say anything if this is newlyDeployed or existing contract (e.g. I care less about the TX and gas if it was already deployed. - but I still want to see the contract address)

**Comment by wighawag** [comment]
It does says "reusing ..." when existing and give the contract address
