### ISSUE TITLE
Question: is there a way to generate EVM assembly 

### ISSUE THREAD

**Issue by playsnook** [wighawag/hardhat-deploy#247]
I'm not sure if that feature relates to hardhat-deploy or to hardhat core. 
I would like to get asm code from hardhat which is generated with `solc --asm`. Is it possible with some config setting through `hardhat.config` or the plugin settings?

Required solc functionality:

![image](https://user-images.githubusercontent.com/85632593/147574993-66eb5898-5179-4b35-be7a-3e7c4b444ea8.png)

**Comment by wighawag** [comment]
Yes, this is not a hardhat-deploy thing, you ll have to override hardhat task to setup the proper solc config

but you want to make sure you do not interfere with hardhat-deploy or other plugin overriding :

see how hardhat-deploy does it : https://github.com/wighawag/hardhat-deploy/blob/db563b0cb1ba287834d68714fc7c446df9803a56/src/index.ts#L325
