### ISSUE TITLE
Clarification on the json structure of "export-all"

### ISSUE THREAD

**Issue by drortirosh** [wighawag/hardhat-deploy#248]
`--export` and `--export-all` are invaluable tools to use the contracts deployment in the target project.

What I don't understand is the idea behind the double-hash of export-all format:
the returned value is hash by the chainId, and each member is a hash by the network name.
The network object returns then contains both name and chainId, and contracts info.
e.g.:
```json
{
    "1337": {
        "dev": {
            "name": "dev", "chainId": "1337", "contracts": { ... }
        }
    }
}
```

I think that for all practical reasons, an array of networks is easer to use, either when a single network is needed, or when a "query" is needed to select multiple networks.

It fact, I parse the above generated structure using:
```js
networks = Object.values(all).map(x=>Object.values(x)).reduce((arr,a)=>([...arr, ...a]))
```
which let me select relevant networks using either name or chainId using a simple `filter()` or `find()`

**Comment by wighawag** [comment]
It is probably a matter of personal preferences.

The nice thing about json hash object is that the structure format guarantee no duplicate network object with same key

Also for the top level object, this is is really useful to have it be taken depending on the current chainId.

As for why each object duplicate name and chainId, it is to keep reusing the exact same format as single export

**Comment by drortirosh** [comment]
I can understand the chainId at the top level, but not the network name underneath... 
for a multi-chain project, a hash by chainId might be useful, but the name as a key isn't.

**Comment by wighawag** [comment]
I get it 
But the benefit of the current structure is that you can have 2 network with the same name

**Comment by drortirosh** [comment]
not sure what you mean: you can't have two networks (say, "dev" ) under different chainIds - in the hardhat-config, the network NAME has to be unique (and also, that network name is a folder name under your "deployments/" folder, so even "hardhat-deploy" requires a globally unique name..

so we end up with a hash by chainId, which contains a single-item hash keyed by the network name...

**Comment by wighawag** [comment]
My point was that thebcurrent format encode that restriction. An array
would not.

**Comment by drortirosh** [comment]
yes, it does.
but the purpose of the auto-generated format is not to encode a restriction, but to be usable. right  now it is usable - but requires parsing before it can be used..

**Comment by wighawag** [comment]
Points taken and I agree that an array would be easier to deal with. 

Now I am not sure how many are using the current export-all format and changing it would be a breaking change.

But might be the best way forward.

**Comment by wighawag** [comment]
From  v0.10.4 onward, the format is as you suggested:

```
export interface Export {
  chainId: string;
  name: string;
  contracts: {[name: string]: ContractExport};
}

export type MultiExport = {
  [chainId: string]: Export[];
};
```
