### ISSUE TITLE
multiple proxies with the same implementation

### ISSUE THREAD

**Issue by estarriolvetch** [wighawag/hardhat-deploy#249]
I am wondering if there is a way to deploy multiple proxies that share the same implementation.

I tried changing the name. However, it seems multiple implementations would be deployed.

**Comment by wighawag** [comment]
Currently you cannot do that, but I agree that hardhat-deploy should allow you to do that.

**Comment by wighawag** [comment]
Note that if you use `deterministicDeployment: true` it will reuse the implementation as long as its code or constructor args did not change

**Comment by wighawag** [comment]
I implemented a solution for it in 0.9.23

you can specify the `implementationName` in the proxy option object and it will use that name for the implementation and so be reused by all proxy using it.

Note that if the constructor args differs, the implementation will be redeployed overwritting the previous one.

**Comment by estarriolvetch** [comment]
@wighawag  That is fast! Thanks for implementing this.

One thing I noticed that is while using the `implementationName`, it still requires me to specify the `contract`. I am not sure if this `contract` will do anything.

**Comment by wighawag** [comment]
currently the process is
- if no `contract` field is present, it will use the `name` field (which is the name of the proxy) to lookup for the contract code.

I could do instead the following
- if no `contract` field is present but `implementationName` is, pick `implementationName` else pick `name`

That indeed sounds logical. One thing I also need to consider is rejecting if `implementationName` == `name`

**Comment by wighawag** [comment]
Done in 0.9.24

**Comment by marcelomorgado** [comment]
Hi @wighawag, I'm trying using this setup but I'm not able to have the same implementation reused.
I've created an repository as example: https://github.com/marcelomorgado/deployment-tryouts

1) What is happening is that the deployment file is being replaced, we can see that the implementation contract was deployed twice:

```
sending eth to create2 contract deployer address (0x3fab184622dc19b6109349b94811493bf2a45362) (tx: 0x8f62c3cb68ae476ac67ea9749828a066fcf881a128111d16a9b68f8670c5b6dd)...
deploying create2 deployer contract (at 0x4e59b44847b379578588920ca78fbf26c0b4956c) using deterministic deployment (https://github.com/Arachnid/deterministic-deployment-proxy) (tx: 0xeddf9e61fb9d8f5111840daef55e5fde0041f5702856532cdbb5a02998033d26)...
deploying "MyProxyAdmin" (tx: 0x85881fac2c99790191808319ca1a7239911b94dee86ffa999042e947ee809dc3)...: deployed at 0x23A4C8E5B176C9E76c69cF5383E9DF6C6AB76B6D with 479002 gas
deploying "MyContract_Implementation" (tx: 0xe94ce0d8d83dd981468190bb0f9d9374e3ef023d59226f98430057b044537d51)...: deployed at 0x0d1C7caa06550610f0A9Bd4FeB446773Ca055F30 with 251192 gas
deploying "MyContractA_Proxy" (tx: 0x4c55925bfef14cac29168e29cfc2d43ea2f9bed3f417bb2d732dc92b1015bb99)...: deployed at 0x57f9A3e824f2C90157a66Aa7b70f683dF5Af9A4b with 545657 gas
executing MyContractA.initialize (tx: 0x0b7d468a0f0ca29a1cdb77edabfe36a2113a38b32db27f4e2bec55aa7ce66e3c) ...: performed with 74482 gas
deploying "MyContract_Implementation" (tx: 0x189e7ed86f60642a4e5ac9cbd3553a282ab7e16056c2dfe254078e3d167c3b6d)...: deployed at 0xe657f549299EeD97C67BE9c58e886e346661c88A with 251192 gas
deploying "MyContractB_Proxy" (tx: 0x3aaa911ec42a686111d9688c5c4cfc09fc23b7968cc3ea36e06e882aa20d2eed)...: deployed at 0x0c91F4A44fb44A104195cB22Af0379Bdb51B7c1E with 545657 gas
executing MyContractB.initialize (tx: 0xcbf8a6fc1b577450542427707c18827da5f2938f9c000ec09a90255fa616ce65) ...: performed with 74482 gas
```
I've also created a test suite, here is the output:

```
  Deployment
    1) should have the same impl
    ✔ should have the same proxy admin


  1 passing (2s)
  1 failing

  1) Deployment
       should have the same impl:

      AssertionError: expected '0x0d1C7caa06550610f0A9Bd4FeB446773Ca0…' to equal '0xe657f549299EeD97C67BE9c58e886e34666…'
      + expected - actual

      -0x0d1C7caa06550610f0A9Bd4FeB446773Ca055F30
      +0xe657f549299EeD97C67BE9c58e886e346661c88A
```

2) Worth noting that I've faced the same behavior (contract overwrite) when configuring both contracts to have the same proxy admin contract using `viaAdminContract`, I was able to work around this by using that way [here](https://github.com/marcelomorgado/deployment-tryouts/blob/master/deploy/02_my_contract_b.ts#L12-L18), not sure if it's intended.

3) Just to double-check the desired behavior is to have all proxies upgraded when changing the implementation contract's code.

Let me know if you need something from me

Thanks!
