### ISSUE TITLE
Which version of Diamond does hh-deploy support?

### ISSUE THREAD

**Issue by junhuang-ho** [wighawag/hardhat-deploy#250]
Hi, which version of [Diamond](https://github.com/mudgen/diamond) does hh-deploy support?

**Comment by wighawag** [comment]
Technically hardhat-deploy support any ERC-2535 diamond, but if you are asking about which one it deployrs, the code is here : https://github.com/wighawag/hardhat-deploy/tree/master/solc_0.7/diamond
