### ISSUE TITLE
Rinkeby and kovam chain ids mixed up

### ISSUE THREAD

**Issue by gen4sp** [wighawag/hardhat-deploy#251]
**Describe the bug**
Hardhat-deploy seems mixed up networks/chainIds

**To Reproduce**
Not sure when it starts

**Expected behavior**
Rinkeby - 4
Kovan - 42

**versions**
- "hardhat": "^2.6.1",
- "hardhat-deploy": "^0.7.0-beta.39",
 - nodejs 16.13

**Additional context**
<img width="718" alt="Screenshot 2022-01-03 at 04 35 44" src="https://user-images.githubusercontent.com/4303628/147940814-de0f4e85-2ef8-416e-af2e-7084512355b3.png">
<img width="960" alt="Screenshot 2022-01-03 at 04 38 22" src="https://user-images.githubusercontent.com/4303628/147940824-940d5de9-a854-467b-b2c7-be4ea35777c9.png">
<img width="248" alt="Screenshot 2022-01-03 at 04 38 47" src="https://user-images.githubusercontent.com/4303628/147940829-649e8458-d54b-448f-a111-d491521e49df.png">

**Comment by wighawag** [comment]
hardhat-deploy does not have any network info by itself, nor hardhat

 you must have misconfigured the network's node urls
