### ISSUE TITLE
How to export ABI to JSON file?

### ISSUE THREAD

**Issue by Dentrax** [wighawag/hardhat-deploy#271]
I was using the following script to export contract's ABI as JSON:

```typescript
const contract = await ethers.getContractFactory("Test")
const token = await contract.deploy(
  "Test"
)

const data = {
  address: nft.address,
  abi: JSON.parse(nft.interface.format('json'))
};

fs.writeFileSync('output.json', JSON.stringify(data, null, 2));
```

I couldn't find much information whether ABI is in JSON format or arbitrary:
```ts
export interface Deployment {
  address: Address;
  abi: ABI;
  ...
}

// ABI

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type ABI = any[]; // TODO abi
```

How can I achieve the same method using hardhat-deploy plugin?

**Comment by wighawag** [comment]
hardhat-deploy have builtin facility for that : https://github.com/wighawag/hardhat-deploy#6-hardhat-export

**Comment by Dentrax** [comment]
Thanks! So exporting a `JSON` file in the `deploy.ts` does not make sense since there is an `export` command?

**Comment by wighawag** [comment]
you can still call the task "export" in your deploy but yes, feel like you do not need it at all
