### ISSUE TITLE
createFixture internals are executed again for every it() call

### ISSUE THREAD

**Issue by radeksvarz** [wighawag/hardhat-deploy#275]
Following the documentation on fixtures  ( https://github.com/wighawag/hardhat-deploy#creating-fixtures ) I prepared a test script, which calls `deployments.createFixture` in its `it()` functions via `beforeEach()`.

I expected that the fixture would be executed only once for the first `it()` and the evm snapshot restore would be used for the consequent `it()` calls.

However hardhat test shows that the `someReadOnlyHeavyCalculationFunction()` and surrounding logs are done for every `it()` function.

I followed this issue https://github.com/wighawag/hardhat-deploy/issues/219 but do not understand the relation of the env var.

code: 

```
/// fixture file
export const myContractInitFixture = deployments.createFixture(
    async ({ deployments, getNamedAccounts, ethers }, options) => {

        // Edit: This is not neeeded as it got called through getDeployedContracts below
        // await deployments.fixture(); 

        console.log("STARTSTART FIXTURE");

        const owner = await getOwnerSigner();

        const { MyContract } = await getDeployedContracts(); // Also assures deployments - see below, so maybe deployments.fixture() is useless up there?

        const { calcOutcome } = await MyContract.someReadOnlyHeavyCalculationFunction();

        console.log(`initial calculation outcome ${calcOutcome}`);

        const tx = await MyContract.connect(owner).writeFunction(
            calcOutcome,
            {value: 2000000000000000000}
        );

        const response = await tx.wait();

        console.log(response);

    },
    "myContractInitFixture"
);

/// deployment setup file
/// based on https://github.com/wighawag/tutorial-hardhat-deploy#full-coverage
/// getDeployedContracts() works perfectly for deployments
export async function getDeployedContracts() {

    // Ensures the deployment is executed and reset (uses evm_snapshot for faster tests)
    const deployedContracts = await deployments.fixture([
        "MyContract",
        "BatchRegister"
    ]);

    // Instantiated contracts in the form of a ethers.js Contract instance
    const contracts = {
        MyContract: (await ethers.getContractAt("MyContract", deployedContracts.MyContract.address)),
		...
    };

    return {
        ...contracts,
    }
}


/// Test file

...

describe("My Contract cases", function () {

    beforeEach(async function () {
        // Assure we have any contract state ready
        await myContractInitFixture ();

        // This is the root cause - since it restores the previous (deployment) fixture
        const { MyContract } = await getDeployedContracts();

...

```
edit: commented out the ` await deployments.fixture(); `
edit2: added the problematic code

**Comment by wighawag** [comment]
could it be that you have other test using other `createFixture` calls ?

see : https://github.com/nomiclabs/hardhat/issues/659

**Comment by radeksvarz** [comment]
I looked into the createFixture code: https://github.com/wighawag/hardhat-deploy/blob/ee100366daa9208586eab6f510ff38986dea7e21/src/DeploymentsManager.ts#L326

That code should be ok.

Is there any way how to check whether the snapshot has been saved?

**Comment by radeksvarz** [comment]
oh, I think the error is here: 

https://github.com/wighawag/hardhat-deploy/blob/ee100366daa9208586eab6f510ff38986dea7e21/src/DeploymentsManager.ts#L327

The code increases the ID anytime the createFixture is called, so it cannot find the already saved fixture in the `this.db.pastFixtures[id];`

I assume the ID increase should be done just before the `saveSnapshot`.

**Comment by wighawag** [comment]
That's expected to increase, createFixture create a fixture, this is not the fixture itself you are supposed to call it once only

**Comment by radeksvarz** [comment]
> i noticed you are calling deployment.fixtures twice though in your createFixture callback
> this could be an issue, not sure why yet, but you should not need it.

I just followed the how to, but also realised / assumed it is not needed.
Anyway even if ` await deployments.fixture(); ` is not there, the behavior is still the same.

I wish there was a full example like you made for deployments.

**Comment by radeksvarz** [comment]
> That's expected to increase, createFixture create a fixture, this is not the fixture itself you are supposed to call it once only

So how can one call / set the state to the existing fixture?

From the code it looks like `createFixture()` is also used for retrieval of the existing fixture - `if (saved) ...`.

https://github.com/wighawag/hardhat-deploy/blob/ee100366daa9208586eab6f510ff38986dea7e21/src/DeploymentsManager.ts#L326
```
      createFixture: <T, O>(func: FixtureFunc<T, O>) => {
        const baseId = '' + ++this.db.fixtureCounter + '::';
        return async (options?: O) => {
          let id = baseId;
          if (options !== undefined) {
            id = id + JSON.stringify(options);
          }
          const saved = this.db.pastFixtures[id];
          if (saved) {
            const success = await this.revertSnapshot(saved);
            if (success) {
              return saved.data;
            }
          }
          const data = await func(this.env, options);
          await this.saveSnapshot(id, data);
          return data;
        };
      },
```

**Comment by wighawag** [comment]
in the example you posted, createFixture is called only once.

the `it` function call the function returned by `createFixture`, not `createFixture` itself

**Comment by radeksvarz** [comment]
> in the example you posted, createFixture is called only once.
> 
> the `it` function call the function returned by `createFixture`, not `createFixture` itself

My apologies, you are correct.

I found the root cause. 

I was calling the deployment fixture **after** the `myContractInitFixture ` in order to get the Contract object. That effectively set the state before the myContractInitFixture.

I updated the example at the beginning of this thread for the reference.

Apologies again.
