### ISSUE TITLE
skipIfAlreadyDeployed flag + proxyOptions not behaving the expected way

### ISSUE THREAD

**Issue by DefiCake** [wighawag/hardhat-deploy#278]
**Describe the bug**
`skipIfAlreadyDeployed` is intended to avoid redeployments. When paired with proxy options, it will skip updates even if the updated implementation contract is named differently from the current implementation. I understand this is because the plugin is checking on the proxy contract instead of the implementation one.

**To Reproduce**

Try to run this, with the variable `contract` pointing to a v1 version, and then run it again with `contract` pointing to a v2 version. It won't be deployed.

```ts
const proxyOptions: ProxyOptions = {
    proxyContract: 'OpenZeppelinTransparentProxy',
    owner: deployer,
    execute: {
      init: {
        methodName: method,
        args: args,
      },
    },
  }

  const deployment = await deploy(contract, {
    from: deployer,
    contract,
    log: true,
    proxy: proxyOptions,
    skipIfAlreadyDeployed,
  })
```

**Expected behavior**
I expect that when using `skipIfAlreadyDeployed` flag set to true, the plugin will make the check on the possible new candidate to implementation, not on the proxy. Thus if the implementation contract is different from the current one, it will go through.

**versions**
 - hardhat-deploy 0.9.29
 - hardhat 2.6.4
 - nodejs 14.18.1

**Comment by wighawag** [comment]
This is to me expected.

as proxy, they won't be redeployed in any case, so skipIfAlreadyDeployed could not apply to the proxy itself.

This is why it is applied to the implementation instead.

If you want the upgrade to go through, you simply have to set skipIfAlreadyDeployed to false


But maybe you are thinking about contract name, and expect that if the contract name specified is different than previous it should be deployed.
If that was the idea, note that hardhat-deploy do not save the name, it just use it to get the artifact and so for hardhat-deploy it does not matter whether you specify the contract by name like you do or if you provide an artifact object.

**Comment by DefiCake** [comment]
> But maybe you are thinking about contract name, and expect that if the contract name specified is different than previous it should be deployed.

Yes that was exactly what I was expecting. Gotcha then. I 'll close it.
