### ISSUE TITLE
deploying "XXXX" (tx: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX)...

### ISSUE THREAD

**Issue by qianduanxinlv** [wighawag/hardhat-deploy#280]
**Describe the bug**
When you get to the deploy function, it doesn't move. There are only "deploying "XXXX" (tx: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX)..."

No error is reported, but the process will not continue

**Comment by qianduanxinlv** [comment]
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/73575444/155678236-4d326322-0237-4a79-97a5-5451ec66694c.png">

**Comment by wighawag** [comment]
what do you mean by

> No error is reported, but the process will not continue

Does the process stop, or it keep waiting for the tx ?

If the latter, can you check the status of that tx on your node ?

**Comment by qianduanxinlv** [comment]
<img width="522" alt="image" src="https://user-images.githubusercontent.com/73575444/155679357-8d42036f-02ad-470b-82b4-63ec659f192a.png">

I did not continue to execute, I can “console deployer” in my code, but after the deploy function, it will not continue, just waiting, and then the following “Contrac1.address” will not be consoled. There should be no problem with the tx. The chain started by hardhat and ganache software cannot be used. They are all in a waiting state. There are three points at the end, The displayed text is “ deploying "PMT721" (tx: 0xd75f210002352c9b96228e58aac1b65d520d583133e8b12ef98eef396c95426e)... ”

**Comment by qianduanxinlv** [comment]
If other people haven't encountered this kind of problem, it may be my problem, but the implementation has been fine before, I don't know why. 
I'll check again

**Comment by wighawag** [comment]
Looks like an issue with your node

**Comment by Doc-Failure** [comment]
Same issue here :/
