### ISSUE TITLE
Add UUPS proxy support

### ISSUE THREAD

**Issue by PatrickAlphaC** [wighawag/hardhat-deploy#282]
There are 2 main openzeppelin proxies, but one currently supported out of the box:

1. Transparent
2. UUPS

[You can find the differences here.](https://docs.openzeppelin.com/contracts/4.x/api/proxy#transparent-vs-uups)

It would be great to support UUPS out of the box as well... I know this would be a little harder.

**Comment by wighawag** [comment]
It is already supported, see : https://github.com/wighawag/hardhat-deploy/issues/146#issuecomment-1003045997

But I could copy the openzeppelin implementation in hardhat-deploy source if that is what you mean ?

**Comment by PatrickAlphaC** [comment]
Gotcha, thanks! 

No I think this is probably better. Make sure people who want to use UUPS know what they are doing.
