### ISSUE TITLE
npx hardhat etherscan-verify not working: Invalid API Key

### ISSUE THREAD

**Issue by fullyallocated** [wighawag/hardhat-deploy#287]
**Describe the bug**
When I try to use the contract verification task, I get an invalid API Key error. I have (properly?) configured hardhat.config.js:

```
networks: {
    ...
    polygonMainnet: {
      url: "https://polygon-mainnet.g.alchemy.com/v2/lP6lP_6hE-DN59hifFzJbMOM8vnZP7-g",
      accounts: [process.env.PRIVATE_KEY],
      verify: {
        etherscan: {
          apiUrl: 'https://api.polygonscan.com/'
        }
      }
    },
    avalancheMainnet: {
      url: "https://api.avax.network/ext/bc/C/rpc",
      accounts: [process.env.PRIVATE_KEY],
    },
  },
  verify: {
    etherscan: {
      apiKey: process.env.SNOWTRACE_API_KEY,
    }
  },
```

**To Reproduce**

I've tried running `npx hardhat --network avalancheMainnet etherscan-verify` and `npx hardhat --network polygonScan etherscan-verify` in the command line, loading in the proper API_KEY for the given chain.

I've set the right values in my .env file. When looking at the explorers, however, the requests don't seem to be reaching the endpoint with the API Key. Maybe the variables aren't being exported correctly?

I ran the same task on Rinkeby, and the contracts were verified successfully—is something going on with my config?

**Expected behavior**

**versions**
 - hardhat-deploy [e.g. 0.9.14]
 - hardhat
 - nodejs

**Additional context**

**Comment by fullyallocated** [comment]
passing in the api key in the CLI through flags. I'm guessing it has to do with .env exports—maybe the order the dependencies are imported?, but I'm honestly too lazy to figure it out atm.

**Comment by wottpal** [comment]
I have the same problem with my configuration. If I pass the apikey as a cli parameter it works correctly. 

cc @wighawag

**Comment by j05u3** [comment]
I even tried hardcoding the api key but same result as you folks:
 
![image](https://user-images.githubusercontent.com/7897132/230224615-24d839ca-199a-4a96-b56e-9ea374325ba2.png)
<img width="801" alt="image" src="https://user-images.githubusercontent.com/7897132/230224750-f037ab87-be5a-4da3-b7dc-1600d98648ce.png">

Same key works though CLI flags.

**Comment by wighawag** [comment]
This is the logic hardhat-deploy uses:

https://github.com/wighawag/hardhat-deploy/blob/55c0b6831744432d889def5c5e7da474fd309f38/src/index.ts#L840-L849

**Comment by j05u3** [comment]
oh, thanks, I haven't tested again but I think I can see the problem now, in my environment variables I had also defined the variable ETHERSCAN_API_KEY (which contains the etherscan.io API Key, not the Polygon scan one)

> This is the logic hardhat-deploy uses:
> 
> https://github.com/wighawag/hardhat-deploy/blob/55c0b6831744432d889def5c5e7da474fd309f38/src/index.ts#L840-L849
