### ISSUE TITLE
Unable to deploy upgradeable contract. "number of arguments do not match implementation constructor"

### ISSUE THREAD

**Issue by aster2709** [wighawag/hardhat-deploy#294]
great plugin. I'm still new to the ways of it. trying to deploy an upgradeable contract

## the contract
```
// SPDX-License-Identifier: MIT
pragma solidity 0.8.13;

import "@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol";

contract BoxV1 is Initializable {
  uint256 public value;
  event Deploy();
  event Increment();

  function initialize(uint256 _value) public initializer {
    value = _value;
    emit Deploy();
  }

  function increment() public {
    value++;
    emit Increment();
  }
}
```
## the deploy script
```ts
import { DeployFunction } from "hardhat-deploy/types"

const deploy: DeployFunction = async (hre) => {
  const { deployer } = await hre.getNamedAccounts()
  await hre.deployments.deploy("BoxV1", {
    from: deployer,
    log: true,
    proxy: "initialize",
    args: [42],
  })
}
deploy.tags = ["BoxV1"]

export default deploy
```
## the error

![image](https://user-images.githubusercontent.com/39130640/160284676-e2e131b2-d108-4f11-bbe6-4f8d53aa0d6a.png)

**Comment by wighawag** [comment]
the issue is that when you use `args` with a proxy it expect both the constructor and the init function to share the same args

The reason for this is for you to allow to use the same contract as immutable contract (Without any proxy) as well as a upgradeable contract without any change.

I use that feature a lot when I develop my frontend and then release on the mainnet. during development it get upgraded automatically but when I deploy I can simply disable the proxy and it sill work the same.


So if you do not expect to deploy without proxy, you ll have to remove the `args` and instead use `execute` or `init`

list this

```
import { DeployFunction } from "hardhat-deploy/types"

const deploy: DeployFunction = async (hre) => {
  const { deployer } = await hre.getNamedAccounts()
  await hre.deployments.deploy("BoxV1", {
    from: deployer,
    log: true,
    proxy: {
      execute: {
        init: {
          methodName: 'initialize",
          args: [43]
        }
      }
    }
  })
}
deploy.tags = ["BoxV1"]

export default deploy
```

**Comment by jwickers** [comment]
I have the same or very similar issue in 0.11.2 (or 0.11.0), but the code worked on 0.10.6:
```
{
    from: deployer,
    proxy: {
      owner: deployer,
      proxyContract: "OptimizedTransparentProxy",
      execute: {
          methodName: 'initialize',
          args: [ deployer ]
      }
    },
  }
```
Now results in `Error: expected 0 constructor arguments, got 1`

The contract does not have a constructor, only an `initialize` function.

I also tried what you posted using `init: { ... }` inside execute but that has the same error.

Did something break in 0.11.x ?

**Comment by wighawag** [comment]
@jwickers oh yes, there is indeed an issue

I just fixed it in 0.11.4

**Comment by wighawag** [comment]
Thanks for reporting!

**Comment by aster2709** [comment]
works @wighawag thanks for addressing. quick follow up. how can you verify the implementation using `etherscan-verify`?

- running the following verifies the proxy instead of implementation
```sh
npx hardhat etherscan-verify --contract-name BoxV1 --network polygon_testnet
```
- is there an option to specify the address you want to verify?

**Comment by aster2709** [comment]
works well.

I couldn't maybe understand the docs to upgrade the proxy. could you tell how `BoxV1` can be upgraded. what changes in the `proxy` property?

**Comment by wighawag** [comment]
@aster2709 the design philosophy of hardhat-deploy script is to be declarative

So for proxy upgrade, you are not supposed to change the proxy config
You just change the code of the implementation and reexecute the deploy command

hardaht-deploy will detect the changes and perform the upgrade, or tell you own to perform it

**Comment by wighawag** [comment]
hmm, that should not be the case, do you have a repo I could try ?

**Comment by aster2709** [comment]
prepared one. still errors out for me on upgrade. here it is, https://github.com/aster2709/hardhat-deploy-template

- `Box.sol` is the basic contract. you can uncomment the `decrement` fn as upgrade :+1:

**Comment by zfogg** [comment]
+1 I can't get 0.11.4 to execute initialize for openzeppelin upgradables

**Comment by wighawag** [comment]
What error do you get ?

@aster2709 I tried your repo and the issue is that your initialize function can only be called once

If you want that you can use 

```
await hre.deployments.deploy("Box", {
    from: deployer,
    log: true,
    proxy: {
      execute: {
        init: { methodName: "initialize",
          args: [42],
        }
      },
    },
  });
```

**Comment by zfogg** [comment]
i'm using openzeppelin's upgradeable contracts so my deploy config looks like this:
<img width="451" alt="image" src="https://user-images.githubusercontent.com/774794/163068613-e8f813e1-97cd-472e-9f84-020b008a9438.png">

**Comment by zfogg** [comment]
this is my trying to deploy on rinkeby btw..

**Comment by aster2709** [comment]
that worked! there's an important observation here.

- `hardhat-deploy` allows to upgrade even if you break the rules of upgradability
- using `@openzeppelin/hardhat-upgrades` deploy script detects them and prevents the upgrade. example:
![image](https://user-images.githubusercontent.com/39130640/163551399-8ece4716-9d44-43fd-b857-93d265eb7aad.png)

@wighawag

**Comment by wighawag** [comment]
Yes, that's a know fact. hardhat-deploy do not implement any verification.
It is your responsibility to ensure you do not do anything wrong with storage layout.

Having said, happy to receive contribution. There is actually a PR implementing this: https://github.com/wighawag/hardhat-deploy/pull/162 but did not found the time yet to look closely

**Comment by aster2709** [comment]
thanks for clarifications and patience. keep building ser :+1:
