### ISSUE TITLE
Slow down blockchain calls during deployment

### ISSUE THREAD

**Issue by CodeForcer** [wighawag/hardhat-deploy#30]
How can I slow down calls to the blockchain during deployment?

Currently I'm rate limited to about 10 calls per second by my JSON RPC provider, unfortunately the deploy plugin makes a bunch of quick successive calls during deployment, hitting my limit.

How can I slow down these calls, or put some sleeping in the middle of the process?

Thanks

**Comment by wighawag** [comment]
buidler-deploy should not make extra call except the one needed for deployment.
Not sure how it can help with your issue.
