### ISSUE TITLE
Update Diamonds With The Latest Changes From the Diamond Standard

### ISSUE THREAD

**Issue by mudgen** [wighawag/hardhat-deploy#32]
The [Diamond Standard](https://eips.ethereum.org/EIPS/eip-2535) recently had a major revision.

The diamond functionality should be updated with the latest version of the standard. Mainly the `diamondCut` function has changed. It now has two more parameters.

The updated code can be found from the Diamond reference implementation: https://github.com/mudgen/Diamond

See this blog post for what has changed in the standard: https://dev.to/mudgen/update-what-s-new-in-the-diamond-standard-eip-fjk

**Comment by mudgen** [comment]
It is really great to see the diamond support in this plugin!  Good job. 

The reference diamond implementations have continued to improve a lot recently.  I see that you have been updating the implementation in buidler-deploy with the improvements. That's great. 

The implementations have recently changed again,  removing some duplicate code.  I think that soon or now the diamond implementations will settle down and stop changing as frequently.

**Comment by mudgen** [comment]
There are now three different reference implementation. The differences between them can be seen here: https://github.com/mudgen/diamond

**Comment by wighawag** [comment]
This is now done
