### ISSUE TITLE
Deploying a Proxy contract with a preexistent ProxyAdmin

### ISSUE THREAD

**Issue by simsbluebox** [wighawag/hardhat-deploy#346]
After reading the documentation and taking a glimpse at the code, I wondered if there is a way to define a ProxyAdmin deployed by another framework (Truffle) before.
Using the `viaAdminContract` seems to search in the current Hardhat deployments db/path, or try to deploy a new one.

```
    proxy: {
    proxyContract: "OpenZeppelinTransparentProxy",
    viaAdminContract: ?
    },

```

**Comment by wighawag** [comment]
you can add a file in the `deployments/<network>` folder and add the abi + address in it

**Comment by simsbluebox** [comment]
Apart from the file, as you suggested, I only provided the ProxyAdmin's owner, and it worked perfectly!
This is the tested snippet:

```
const result = await deploy(ContractName,{
    from: deployer,
    proxy: {
      proxyContract: "OpenZeppelinTransparentProxy",
      owner: ProxyAdminOwner,
      viaAdminContract: {
        name: "ProxyAdmin"
      },
    },
    log: true,
});

```
Thanks for your help @wighawag !
