### ISSUE TITLE
Incorrect DiamondLoupeFacet implementation used in Diamond deployments

### ISSUE THREAD

**Issue by TSnark** [wighawag/hardhat-deploy#352]
**Describe the bug**
Due to a name collision the extended [artifact](https://github.com/wighawag/hardhat-deploy/blob/master/extendedArtifacts/DiamondLoupeFacet.json
) used for DiamondLoupeFacet in the [helper source](https://github.com/wighawag/hardhat-deploy/blob/f85305ba6ffef2750d64ade7509e7fd65a05bc27/src/helpers.ts#L55) refers to the  [DiamondLoupeFacetWithoutSupportsInterface.sol](https://github.com/wighawag/hardhat-deploy/blob/master/solc_0.8/diamond/facets/DiamondLoupeFacetWithoutSupportsInterface.sol) implementation.

**To Reproduce**
Deploy a diamond using the plugin

**Expected behavior**
Use [DiamondLoupeFacet.sol](https://github.com/wighawag/hardhat-deploy/blob/master/solc_0.8/diamond/facets/DiamondLoupeFacet.sol)

**versions**
 - hardhat-deploy: 0.11.4
 - solidity: ^0.8.0

**Additional context**
From diamond discord:
@wighawag: 

> DiamondLoupeFacetWithoutSupportsInterface is not used indeed, it was coded to test the idea of letting user implements its own ERC165 mechanis separatly

**Comment by wighawag** [comment]
Oh I see, `DiamondLoupeFacetWithoutSupportsInterface.sol` is wrong.

So the issue you encounter is that the DiamondLoupeFacet inside `DiamondLoupeFacetWithoutSupportsInterface.sol`  is used instead of the one in `DiamondLoupeFacet.sol`, right ?

**Comment by TSnark** [comment]
Exactly!

**Comment by wighawag** [comment]
This is bad, I ll fix that as soon as I can, thanks for reporting!

**Comment by TSnark** [comment]
Cheers 🙏

**Comment by wighawag** [comment]
Should be fixed in 0.11.12
