### ISSUE TITLE
Upgrading Proxy Contracts Doesn't Work with Multiple Owners (potential fix included)

### ISSUE THREAD

**Issue by blakewest** [wighawag/hardhat-deploy#36]
Hi, I'm trying to use the library to upgrade my contracts, using Proxies. Specifically, I want to have the proxy owned by a different admin than the implementation. This is pretty much [required](https://blog.openzeppelin.com/the-transparent-proxy-pattern/), as OZ states in the article that you link to in the docs. You mention in the docs that if we do this though, `Note that for the second invocation, this deployment will fails to upgrade the proxy as the from which is deployer is not the same as the proxy's owner : greeterOwner`. 

Indeed, if I try to do this, it fails. But I don't think it has to fail. In digging around the source code, I determined that I believe a two-line change could fix this. I might be going about this in a silly way, but here's what I found:

[here](https://github.com/wighawag/buidler-deploy/blob/e534fcdc7ffffe2511a48c04def54ae1acf532bc/src/helpers.ts#L869)
```
-    const currentOwner = await read(proxyName, "proxyAdmin");
+   const currentOwner = await read(proxyName, {from: owner}, "proxyAdmin");
```

[and here](https://github.com/wighawag/buidler-deploy/blob/e534fcdc7ffffe2511a48c04def54ae1acf532bc/src/helpers.ts#L889)
```

-                const executeReceipt = await execute(proxyName, Object.assign({}, options), "changeImplementation", implementation.address, data);
+                const executeReceipt = await execute(proxyName, Object.assign({}, options, {from: owner}), "changeImplementation", implementation.address, data);
```

These changes make my tests go from red to green. Without it, I get the error `Error: Transaction reverted: function selector was not recognized and there's no fallback function`. It seems to stem from the fact that you're trying to call the proxy contract from a different address than it's owner, which I believe means the proxy will never respond to functions that live on the proxy itself (such as `proxyAdmin` or `changeImplementation`). 

The `owner` in the above file is already getting pulled from `getProxyOwner`, so it seems reasonable to use it when calling functions on the Proxy contract itself at all times anyway. Like you have the guard check that the "currentOwner" equals the "owner", but this check feels unnecessary during deployment. If someone wants to transfer ownership, I would expect that to happen as a separate migration, outside of a deploy call. 

What are your thoughts on this fix? What other issues might come up? I think if we had it, proxy deployments with different owners for the proxy and the implementation would start to "just work" when you upgrade. 

Thanks for your consideration! I like the library so far!

**Comment by blakewest** [comment]
I'll also add that without this fix, I'm left to either fork the library (which I generally prefer not to do if I can help it), or I'm left to write a bit of a goofy hack around it that looks like the following:
```js
async function upgrade(bre, contractName, deployOptions) {
  const { deployments, ethers, getNamedAccounts } = bre;
  const { deploy, log } = deployments;
  const { protocol_owner, proxy_owner } = await getNamedAccounts();
  log("Attemping to upgrade", contractName);

  // deployOptions.from = protocol_owner;
  deployOptions.from = protocol_owner
  deployOptions.proxy = {owner: proxy_owner};

  const signers = await ethers.getSigners();
  const proxyOwnerSigner = signers[1];

  log("Deploying implementation...");
  const implementationReceipt = await deploy(contractName + "_Implementation", deployOptions);
  log("Implementation deployed to", implementationReceipt.address);

  if (!implementationOptions.contract) {
    implementationOptions.contract = name;
  }

  const proxyVersion = await deployments.get(contractName + "_Proxy");
  const regularVersion = await deployments.get(contractName);
  const proxy = await ethers.getContractAt(proxyVersion.abi, proxyVersion.address, proxyOwnerSigner);

  // If we want to run any post upgrade functions or initializations or anything after the implementation deployment, 
  // then we would need to actually populate the data here. See https://github.com/wighawag/buidler-deploy/blob/e534fcdc7ffffe2511a48c04def54ae1acf532bc/src/helpers.ts#L854 for more
  const data = "0x";
  log("Changing implementation...");
  await proxy.changeImplementation(implementationReceipt.address, data);
  log("Upgrade complete");
}
```

As a separate usability thing, I think it could be nice to add an additional function that's part of deployments called `upgrade(contractName, deployOptions)`, which assumes it was deployed via proxy, and handles choosing the right signers for you based on the last deployment.

**Comment by wighawag** [comment]
HI @blakewest thanks for the feedback

> Indeed, if I try to do this, it fails. But I don't think it has to fail. In digging around the source code, I determined that I believe a two-line change could fix this. I might be going about this in a silly way, but here's what I found:

Note that only the example fails. it is definitely possible to call the upgrade from the new owner. and if the new owner is a contract, buidler-deploy will output you the transaction data to execute from that new owner

**Comment by wighawag** [comment]
> As a separate usability thing, I think it could be nice to add an additional function that's part of deployments called upgrade(contractName, deployOptions), which assumes it was deployed via proxy, and handles choosing the right signers for you based on the last deployment.

That sounds good. Note that the idea of how it is implemented is that you always specify the new state and buidler-deploy take care of the rest

so you if you specify a new implementation, it will perform the necessary transition. if you pass an upgrade function it will call it too.
I did not have time to look closely I what you want to do but you should be able tthe deploy function to make an upgrade

**Comment by wighawag** [comment]
> like you have the guard check that the "currentOwner" equals the "owner", but this check feels unnecessary during deployment. If someone wants to transfer ownership, I would expect that to happen as a separate migration, outside of a deploy call.

The reason it is like that it is because the deploy function define what the new state will be. So as you said, if you want to change ownership, you ll transfer it in another script. If you do not want to change ownership, you leave the owner field as it is.

the check here is to tell you that if you want to transfer ownership, you need to do it separatly

**Comment by wighawag** [comment]
re the example

you can have one script that is executed only if no proxy was ever deployed :

```
module.exports = async ({ getNamedAccounts, deployments, getChainId }) => {
  const { deploy } = deployments;
  const { deployer, greeterOwner } = await getNamedAccounts();
  await deploy("Greeter", {
    from: deployer,
    proxy: {
      owner: greeterOwner,
      methodName: "postUpgrade"
    },
    args: ["arg1", 2, 3]
  });
};
```

then you have another script that make the upgrade whenever the impl changes:

```
module.exports = async ({ getNamedAccounts, deployments, getChainId }) => {
  const { deploy } = deployments;
  const { deployer, greeterOwner } = await getNamedAccounts();
  await deploy("Greeter", {
    from: greeterOwner,
    proxy: {
      owner: greeterOwner,
      methodName: "postUpgrade"
    },
    args: ["arg1", 2, 3]
  });
};
```

**Comment by blakewest** [comment]
> then you have another script that make the upgrade whenever the impl changes:
I had tried this, and I just confirmed this does not appear to work for me. Here is my original deploy code:

```js
var creditDeskDeployResult = await deploy("CreditDesk", 
  {
    from: protocol_owner, 
    proxy: {owner: proxy_owner, methodName: "initialize"}, 
    gas: 4000000, 
    args: [pool.address],
    libraries: {["Accountant"]: accountant.address}
  }
);
```

And in my tests, I was doing this...
```js
describe.only("Upgrading", () => {
  beforeEach(async () => {
    await deployments.run();
  });
  it("should allow for upgrading the logic", async () => {
    const { protocol_owner } = await getNamedAccounts();
    const creditDesk = await getDeployedContract(deployments, "CreditDesk");
    expect(typeof(creditDesk.someBrandNewFunction)).not.to.equal("function");

    await upgrade(bre, "CreditDesk", {contract: "FakeV2CreditDesk"});
    const newCreditDesk = await getDeployedContract(deployments, "CreditDesk");
    
    expect(typeof(newCreditDesk.someBrandNewFunction)).to.equal("function");
    const result = String(await newCreditDesk.someBrandNewFunction());
    expect(result).to.bignumber.equal(new BN(5));
  });
}

async function upgrade(bre, contractName, deployOptions) {
  const { deployments, ethers, getNamedAccounts } = bre;
  const { deploy, log } = deployments;
  const { protocol_owner, proxy_owner } = await getNamedAccounts();
  log("Attemping to upgrade", contractName);

  deployOptions.from = proxy_owner
  deployOptions.proxy = {owner: proxy_owner};
  await deploy(contractName, deployOptions);
}
```

But this fails with the error I mentioned above `Error: Transaction reverted: function selector was not recognized and there's no fallback function`. Am I doing something wrong here?

**Comment by wighawag** [comment]
Interesting, the error is not familiar. Where do you think it comes from ?

Note that instead of `deployments.run` you should use `deployments.fixture` as it speed up the tests. But in itself that should not cause issue.

If you have a repo that reproduce the issue, that would be great.

**Comment by blakewest** [comment]
@wighawag I'll see if I can put together a repo for you. But it definitely comes from who the signer is on the transaction. As mentioned above, if I make the changes I wrote at the top, then it passes. My guess is that because no `from` is passed into the [read](https://github.com/wighawag/buidler-deploy/blob/e534fcdc7ffffe2511a48c04def54ae1acf532bc/src/helpers.ts#L869) or [execute](https://github.com/wighawag/buidler-deploy/blob/e534fcdc7ffffe2511a48c04def54ae1acf532bc/src/helpers.ts#L889) call , that it defaults to the first position signer, which is not the same as the proxy's signer. Hence why I was suggesting to always pass in the proxy signer to those calls.

**Comment by wighawag** [comment]
Ok, yes sorry, could not look closer.

Where is the exact lines that the change is made?

Here : https://github.com/wighawag/buidler-deploy/blob/e534fcdc7ffffe2511a48c04def54ae1acf532bc/src/helpers.ts#L887 I see that the `from` is taken from the options passed to `deploy`

**Comment by wighawag** [comment]
you might also want to try  `buidler-deploy@next` (the code is from the master branch) it introduces some breaking changes but with the resources I have it is probably the only version I ll be able to maintain.

**Comment by blakewest** [comment]
@wighawag OK, I found the bug. You're right that for the execute call, options is handed in from the deploy options, and so if you specify the proxy owner in both places, it would work. However, the bug is [here](https://github.com/wighawag/buidler-deploy/blob/e534fcdc7ffffe2511a48c04def54ae1acf532bc/src/helpers.ts#L869) in the `read` function, which does not hand in the options, and so ends up probably using the default signer (not the proxy owner). 

So I think the fix would just be to do: 
```js
const currentOwner = await read(proxyName, Object.assign({}, options), "proxyAdmin");
```

I could put up a fix for this. Though if you're working on a new branch, you would have to let me know the best way to contribute. Also another question... if I specify `proxy_owner` in both places (from and {proxy: {from}}), would that change the owner of the implementation contract? I'd want to maintain the `protocol_owner` as the owner of the implementation contract, while also keeping the `proxy_owner` as the admin of the proxy.

**Comment by wighawag** [comment]
Nice, thanks! good catch!

I fixed it in buidler-deploy@next.

for contribution, the branch I am working on is master.

planning to release soon, but I have been saying that for a while :)

Re from, there is no `{proxy:{from`
but the owner will not change, even if you change the `{proxy {owner`
to change the owner you have to call `changeProxyAdmin`

**Comment by blakewest** [comment]
@wighawag cool. I see the `master` branch doesn't include TransparentProxy for sol 0.6 anymore? I see it's now only in sol 0.7 folder..? I'm on so. 0.6, so will this break my usage of proxies? If so, is it possible to keep TransparentProxy in the 0.6, for backwards compatibility?

Also re: the `proxy: from`. Sorry yeah I didn't mean the owner of the proxy, I meant the owner of the implementation. Eg. on the initial deploy I mark it as `deploy(contractName, {from: protocol_owner, proxy: {owner: proxy_owner}}`, but then on the upgrade, I would do... `deploy(contractName, {from: proxy_owner, proxy: {owner: proxy_owner}}`. Will that automatically change my implementation owner to be the proxy owner? 

Thanks!

**Comment by wighawag** [comment]
The proxy is actually already compiled, so 0.7 or 0.6 will not affect you. Also if your contract was already deployed, the api remains the same so the functionality should still work

re `deploy(contractName, {from: protocol_owner, proxy: {owner: proxy_owner}}` followed by `deploy(contractName, {from: proxy_owner, proxy: {owner: proxy_owner}}` 
the first execution will create the implementation with msg.sender so if you use `msg.sender` to set your owner, then yes in the 2nd execution, it will have a different owner.

For my contract, I usually never give the deployer of a contract special role and instead pass the owner I want as part of the constructor.

Also note that in the context of a proxy the owner of an implementation would only affect the implementation when executed directly (not through the proxy)

But if you feel like the API would benefit in separating the `from` for Proxy from the `from` for the implementation,. I would happy to accomodate that in the next version.

One possible idea is to allow  `deploy({proxy` to pass an already deployed implementation. this way you deploy the implementation first and then execute the upgrade.

I ll think about it. Another option I am considerring following our conversation is adding an explicit `upgrade` helper

**Comment by blakewest** [comment]
@wighawag yeah the already deployed implementation idea could work. Another thought would be to allow for an arbitrary callback that gets handed the deployed implementation and the `bre`. Sort of like a mini deploy script. Then in that callback, I could call `transferOwnership` to the other account (not the deployer account).

For context, the reason I'm not passing in the owner to the constructor is because I'm using Open Zeppelin's `Ownable` contract, which just doesn't work that way. And of course I could fork it, but it's very nice to be able to 100% re-use code that's already been heavily audited and battle tested.

**Comment by wighawag** [comment]
@blakewest I am thinking to simply have an extra field `implementationDeployer` to allow user to specify a different deployer for the implementation

But I am still struggling to see why you care about the implementation's owner. When the implementation is called via a proxy, the owner set in the constructor will not be reachable as DELEGATE_CALL use the storage of the proxy, not the implementation

Are you planning to use the implementation contract both as a standalone contract and  through the proxy simultaneously even though they will not share the same storage ?

**Comment by blakewest** [comment]
Maybe I'm thinking about this wrong, but my thinking has been...
Due to the transparent proxy pattern, you need to have two different "owners". One for the proxy, and one for the logic. This is because anytime I call the proxy with the proxy admin (owner 1), it will never delegate calls to the logic contract. And anytime I call with the logic owner (owner 2), it will never allow me to call the proxy's methods such as `changeAdmin` or `changeImplementation`. Perhaps also relevant is that I'm inheriting from OpenZeppelin's `Ownable` contract, and I have several methods on my logic contract, which only the owner can call. On top of this, since the `Ownable` contract just sets the owner to be `msg.sender` by default, then I need to sign the first deploy transaction with the "logic owner". And then I need the proxy to be owned by someone else. 

I believe this issue could be solved if the `Ownable` contract allowed me to set the owner in the `initialize` method, but it doesn't. I could also solve this through your `implementationDeployer` thing as well, because I could deploy with the "proxy admin" account, and then set the "logic owner" in the `initialize` method, and the proxy itself could be owned by the proxy admin. 

Am I missing something though?

**Comment by wighawag** [comment]
Having 2 different owner is fine (one for proxy management and one for logic) but the second owner (non-proxy) cannot be set via the implementation constructor as it will use the storage of the implementation and not the proxy.
You'll have to set the owner via your own method (I think Ownable contains `transferOwnership`, that you call through the proxy option `methodName` 

Note that the `implementationDeployer `option will actually not help you as this only affect implementation storage

**Comment by wighawag** [comment]
Note that my transparent proxy implementation do not prevent admin from calling other function (unless they clash). it only prevent non-admin from calling admin-function and proxy related getters

**Comment by blakewest** [comment]
> Having 2 different owner is fine (one for proxy management and one for logic) but the second owner (non-proxy) cannot be set via the implementation constructor as it will use the storage of the implementation and not the proxy.
> You'll have to set the owner via your own method (I think Ownable contains `transferOwnership`, that you call through the proxy option `methodName`

Right, yes. It was set via an initializer on the implementation. 

> Note that my transparent proxy implementation do not prevent admin from calling other function (unless they clash). it only prevent non-admin from calling admin-function and proxy related getters

Oh! But this is great! So then we really can just have one owner for both. Because the two methods on the proxy do not conflict with any of our methods on the logic contract. I think this actually is the key. We'll just go this route.

**Comment by wighawag** [comment]
I probably should rename the Proxy as it is not the same pattern as openzepelin one.
Admin need to be careful, but I am going to add selector clash to avoid the potential issue

**Comment by blakewest** [comment]
I think that's a good idea to rename it.

**Comment by wighawag** [comment]
in hardhat-deploy I renamed the contract and is now fully EIP-173 compliant.
This should resolve your issue
