### ISSUE TITLE
Does external deployments config work with `hh node --no-deploy`?

### ISSUE THREAD

**Issue by jack-wombat** [wighawag/hardhat-deploy#408]
Does hardhat-deploy skips loading existing and external deployments  when `--no-deploy` is present? I was looking for a way to have local hardhat simulate mainnet as much as possible. I came across to the external deployments config in https://github.com/wighawag/hardhat-deploy/issues/56. 

However, when I run `hh node` with the `--no-deploy` flag, the `await deployments.all()` is empty. But `await deployments.getArtifact()` still seem to work. Most of my code is using `deployments.get()` which relies on `deployments.all()`.

**Comment by jack-wombat** [comment]
Ping @wighawag

**Comment by wighawag** [comment]
hmm, it should work. DO you have reproduction repo I could look at ?

**Comment by jack-wombat** [comment]
Turns out I was using some old versions of hardhat. Once upgrade to latest, i'm able to use it.

**Comment by jack-wombat** [comment]
I figured this out. I need to add also localhost to the external deployments config.

Example:
```
config.external = {
    deployments: { [Network.HARDHAT]: external_deployments, [Network.LOCALHOST]: external_deployments },
  }
```
