### ISSUE TITLE
Running `buidler deploy` having set `defaultNetwork` and without `--write true` doesn't write deployments to disk

### ISSUE THREAD

**Issue by lmcorbalan** [wighawag/hardhat-deploy#41]
If you set `defaultNetwork` in the `buidler.config.js` file, in my case I was using `defaultNetwork: 'rinkeby'`, it makes necessary to use `--write true` when running deploy task.
I was confused since docs says the default value for --wait is true.

Great plugin btw!!!

**Comment by wighawag** [comment]
Thanks @lmcorbalan for the bug report!
It definitely should not require you to set --write true
I ll have a look

**Comment by wighawag** [comment]
fixed in hardhat-deploy@0.7.0-beta.13
