### ISSUE TITLE
Deployment retrying (by saving pending tx) - need more info

### ISSUE THREAD

**Issue by n00b21337** [wighawag/hardhat-deploy#435]
Would like a bit of more info on this feature mentioned

"deployment retrying (by saving pending tx): so you can feel confident when making a deployment that you can always recover."

What does it mean pending tx is saved? Where is it saved and how can it be used? 
What I am thinking is that maybe I want to cancel or speed up pending trx, how can I do that and is there a function I could call to see what trx are pending and which one I can interact with? I know I can do it manually by just checking the chain and doing manual trx with the same nonce, wondering what does this library offer and what I could expect to do?

**Comment by wighawag** [comment]
So the `hardhat deploy` generate a file with the info about the contract being deployed when you send a tx
if you interupt the command and execute it again, it will retrieve that fails and wait again for the tx, if the tx it still pending it will ask you fi you want to retry with a higher gas
