### ISSUE TITLE
Is it possible to reuse implementation when multiple proxy refers to the same implementation?

### ISSUE THREAD

**Issue by drop19** [wighawag/hardhat-deploy#446]
For example:
Proxy A -> Impl X
Proxy B -> Impl X

**Comment by wighawag** [comment]
Yes you 

can use `implementationName`

so you first deploy your implementation via a normal deploy call and name it whatever you want
```
await deploy("MyImplementation", ...)
```

then when deploying proxies

```
await deploy("ProxyA",  {from: ..., proxy: {implementationName: "MyImplementation"}})
```
