### ISSUE TITLE
deterministic deployment how to transferownership?

### ISSUE THREAD

**Issue by vseae** [wighawag/hardhat-deploy#467]
I have deployed a contract using a deterministic deployment method. This contract has an owner address. How can I change the owner address to my personal wallet address instead of the create2 contract address?

**Comment by wighawag** [comment]
If the current owner is the create2 factory then you cannot change it

You need to use proxy that allow to set the owner in their constructor

**Comment by vseae** [comment]
Are you suggesting that I manually pass my personal address in the constructor of the deployed contract in order to set it as the owner?

```
constructor(address owner){
_transferownership(owner);
}
```

**Comment by wighawag** [comment]
yes the proxy need to have a mechanism to let you set the owner and the constructor is the best place for it

**Comment by vseae** [comment]
Thank you for your answer
