### ISSUE TITLE
ethers v6  no matching function

### ISSUE THREAD

**Issue by vseae** [wighawag/hardhat-deploy#470]
After upgrading my hardhat-ethers and ethers to version 6, I encountered some issues. Here is the modified code:

```javascript
const helloProxy = await ethers.getContractAt(
  depHello.abi,
  depHelloProxy.address
);

const tx = await helloProxy.grantRole(role, proxy.address);
await tx.wait();
```

**TypeError: no matching function (argument="key", value="address", code=INVALID_ARGUMENT, version=6.6.5)**

**This code works fine in ethers v5.**

**Comment by the-real-astro** [comment]
@vseae This is a ethers v6 and hardhat-ethers issue. You can use the address on the deployment itself and freshly deployed contracts via factory have a `getAddress(): Promise<string>` method.

**Comment by vseae** [comment]
Thanks
