### ISSUE TITLE
The property "mint" does not exist on the type "BaseContract".

### ISSUE THREAD

**Issue by vseae** [wighawag/hardhat-deploy#475]
```
  const demo = await ethers.getContract(
    "Demo"
  );
```
After upgrading to ethers v6 and using the recommended version of the hardhat-ethers library from this repository, when I call getContract and try to invoke the mint method on the returned contract, it shows an error message saying "The property "mint" does not exist on the type "BaseContract"."

**1.Why is the returned type now BaseContract instead of Contract?**

**2.Apart from using the 'any' type, how should I fix it?**

**Comment by wighawag** [comment]
This issue should be moved to https://github.com/wighawag/hardhat-deploy-ethers/
hardhat-deploy does not care what library you are using: viem, ethers, web3 ....
