### ISSUE TITLE
Crash with companion networks on hardhat ^2.16

### ISSUE THREAD

**Issue by nataouze** [wighawag/hardhat-deploy#490]
**Describe the bug**
When using `^hardhat@2.16.0` with companion networks configured for non-dev networks, a crash occurs.

This is due to the change of signature of hardhat's `createProvider` function.

https://github.com/NomicFoundation/hardhat/blob/aebd01983febb777c0e8cca216a3884980128b90/packages/hardhat-core/src/internal/core/providers/construction.ts#L50-L56

Proposed fix #488

**Comment by Arachnid** [comment]
Would love to see this merged, as it's currently a blocker for us!

**Comment by wighawag** [comment]
Available in v0.11.43 !
