### ISSUE TITLE
Allow passing of arrays to entries in namedAccounts

### ISSUE THREAD

**Issue by adklempner** [wighawag/hardhat-deploy#53]
`buidler-deploy` allowed passing arrays of number like so:
```
namedAccounts: {
  deployer: 0,
  users: [1, 2, 3]
}
```
which caused `getNamedAccounts()` to return:
```
{
  deployer: "0x1234...",
  users: ["0x5678...", "0x9876...", "0x5432"]
}
```

When using version `^0.7.0-beta.28` with the configuration above, it returns:
```
{
  deployer: "0x1234..."
}
```

It would be nice if the old behavior was implemented again.

**Comment by wighawag** [comment]
Hi @adklempner thanks for the feedback

This was changed to get better typescript typing.

There is now `getUnnamedAccounts` though that return all teh accounts not referenced in the `namedAccounts` config

I am considering adding a `configuration` config that would allow any types. that could be used for more than addresses
