### ISSUE TITLE
When using viaIR, the contract will fail to validate

### ISSUE THREAD

**Issue by ben46** [wighawag/hardhat-deploy#540]
I am using the base sepolia network to verify an upgradable contract.

# Successful

You can verify success using this, which is generated by the hardhat-verify plugin.

[suc](https://gist.github.com/ben46/cfee06c5cd74e02be971ef82fd840950)

# failed

This formData generated by hardhat-deploy fails verification.

[failed](https://gist.github.com/ben46/be6164588f6f720d7b87f2b96831f1a4)

**Comment by wighawag** [comment]
does it work against sourcify ?

**Comment by ben46** [comment]
> does it work against sourcify ?
> 
> Also are they same contracts ?

found solutions here: https://hardhat.org/hardhat-runner/docs/reference/solidity-support#support-for-ir-based-codegen
