### ISSUE TITLE
Support for Ethers.js@v6.0.0

### ISSUE THREAD

**Issue by mgroovyank** [wighawag/hardhat-deploy#542]
I was trying to use latest version of Hardhat(v2.22.3) with hardhat-ethers plugin. The hardhat-ethers plugin is compatible with latest version of ethers.js(v6.0.0). But when I tried to install hardhat-deploy plugin(v0.12.2)  and hardhat-deploy-ethers plugin, I saw some errors. 

![image](https://github.com/wighawag/hardhat-deploy/assets/40556224/af888fee-f53a-428e-85bc-26199e0d7283)

It seems hardhat-deploy plugin is still not compatible with ethers.js(v6.0.0).

If my understanding is correct, when can we expect support for ethers.js@v6.0.0?

**Comment by wighawag** [comment]
what do you mean by hardhat-deploy do not support ethers.js v6 ?
What error do you see ?

hardhat-deploy is agnostic to which lib you use and  it do not expose any lib specific api and you can use any you like

**Comment by mgroovyank** [comment]
@wighawag  Thank you for your reply.

`hardhat-deploy is agnostic to which lib you use and it do not expose any lib specific api and you can use any you like`

Is this the same in case of hardhat-deploy-ethers package as well?

**Comment by wighawag** [comment]
> Is this the same in case of hardhat-deploy-ethers package as well?

No  hardhat-deploy-ethers is here to use ethers with hardhat-deploy.

The error seems to indicate that hardhat-deploy-ethers expect an earlier version of hardhat-deploy

If this is case, please open an issue here instead : https://github.com/wighawag/hardhat-deploy-ethers

**Comment by mgroovyank** [comment]
Opened [#37](https://github.com/wighawag/hardhat-deploy-ethers/issues/37).
Closing this one.
