### ISSUE TITLE
Feature Request: batch deploy transactions

### ISSUE THREAD

**Issue by gitpusha** [wighawag/hardhat-deploy#55]
It would be great to have a flag like `--batch` and have `hardhat-deploy` evaluate the total number of deployments to be done and the sequence and then send all transactions off to the network in one go with their respective sequential nonces.

**Comment by wighawag** [comment]
This is not really possible as some of the deploy step depends on the result of others

Note that this can be done manually in your script. Currently the deploy function always wait for the deploy tx to be mined, but you can use the low level `deployments.save` and use of ethers factory for example

**Comment by gitpusha** [comment]
True - I guess this would only work for `create2s`
