### ISSUE TITLE
Possible Hack / Hijack of Deployment

### ISSUE THREAD

**Issue by Maurechi** [wighawag/hardhat-deploy#550]
**Describe the bug**
![Screenshot 2024-06-13 at 16 05 26](https://github.com/wighawag/hardhat-deploy/assets/71376233/38ce4217-00a0-4aec-b952-c0d17865bb69)
Our deployment was hijacked and all our funds were used as transaction fees for a funnel address. As you can see, the transaction that is logged by the library is the hijacked one https://etherscan.io/tx/0xd3bd7e45d4355e98c0fcd092f9f9a71c6c251b07d38b9a01ff04c610d2e0f5c8

This happened with 2 other contracts that we were deploying as well.

**To Reproduce**
This happened while running all the deployment scripts, the most basic example is this 
```typescript
import { FACETS } from "../utils/deployment/facets";
import { ethers } from "hardhat";
import { DeployFunction } from "hardhat-deploy/types";
import { HardhatRuntimeEnvironment } from "hardhat/types";

const DIAMOND_LOUPE_FACET_NAME = FACETS.DiamondLoupeFacet.name;
const func: DeployFunction = async function (hre: HardhatRuntimeEnvironment) {
    const { deployments } = hre;
    const provider = ethers.provider;
    const from = await provider.getSigner().getAddress();
    const { deploy } = deployments;

    await deploy(DIAMOND_LOUPE_FACET_NAME, {
        from,
        args: [],
        log: true,
        deterministicDeployment: true,
    });
};
export default func;
func.tags = [DIAMOND_LOUPE_FACET_NAME];

```

**Expected behavior**
We have used this exact pattern for deploying other contracts on Arbitrum and BSC. But on Ethereum it got hijacked.

**versions**
"hardhat-deploy": "^0.11.43"
"hardhat": "^2.19.1",
 - nodejs

**Additional context**

**Comment by jdbertron** [comment]
This is super vague. Can you explain clearly ?

**Comment by Maurechi** [comment]
As said above this was not a library issue in the end.
