### ISSUE TITLE
Feature request: allow to pass afterDeploy script

### ISSUE THREAD

**Issue by jsidorenko** [wighawag/hardhat-deploy#57]
It would be very handy to be able to have `--afterDeploy <filename>` param that would be executed in the same way `hardhat run <filename>` works.
Imagine you need to generate some additional internal files with the deployment data.

**Comment by wighawag** [comment]
hi @jsidorenko thanks for the feedback.
Could you not achieve that via `hardhat --network <networkName> deploy && hardhat --network <networkName> run <filename>` ?

**Comment by jsidorenko** [comment]
Yes, you could. The issue comes when you want to run deployment with the `--watch` flag and want to execute some script after each re-deployment

**Comment by wighawag** [comment]
ha yes good point.
What about having that as a deploy script itself ?

I am just trying to ensure I only add what is striclty necessary as hardhat-deploy is already quite complex as it is :)

**Comment by jsidorenko** [comment]
> What about having that as a deploy script itself ?
This is what I actually did :) and that looks like a hack..
The real problem with that hack comes when you connect deployment scripts via 'external' setting, as you want it to be executed in the caller's context. Let's say you connect contracts via npm, then you definitely can't add a generic deploy script as you don't know the context it's gonna be executed.

In theory, you could simply require the provided js file, take the exported function like in a deployment script and execute it by passing the same 'hre' object

**Comment by wighawag** [comment]
I am not sure I follow,
the external deploy scripts will always be executed first.
then if you hack deploy script is to be executed at the end, you can be sure it will have the same context as a script executed afterward.

**Comment by jsidorenko** [comment]
Sorry, I was thinking about adding the additional deploy script to the externals.
You're right! If we add it to the main project (that injects external contracts), then the context will be correct.

**Comment by wighawag** [comment]
I ll close the issue but feel free to open again if you think a afterDeploy hook is actually needed
