### ISSUE TITLE
hardhat-deploy Error: function "facetAddress" will shadow "facetAddress". Please update code to avoid

### ISSUE THREAD

**Issue by mudgen** [wighawag/hardhat-deploy#61]
Someone is getting this error when trying to use a diamond with hardhat:
`hardhat-deploy Error: function "facetAddress" will shadow "facetAddress". Please update code to avoid`

This error is happening because in DiamondLoupeFacet.sol the facetAddress function name gets shadowed with a variable.

This is fixed in the most recent versions of diamond implementations.  Can the diamond implementation of hardhat-deploy be updated to the newest version? 

https://github.com/mudgen/diamond-3

**Comment by ezynda3** [comment]
Any update on this?

**Comment by wighawag** [comment]
HI @ezynda3 I have been working on a rework for diamond support. it is in the [diamond branch](https://github.com/wighawag/hardhat-deploy/tree/diamond)

I need to test it more and merge latest from master

**Comment by ezynda3** [comment]
@wighawag awesome! Thanks for the great work on this plugin!

**Comment by wighawag** [comment]
With the new version, this should be fixed
