### ISSUE TITLE
hardhat node task bug deploys to ropsten defaultNetwork

### ISSUE THREAD

**Issue by gitpusha** [wighawag/hardhat-deploy#63]
For ref see: https://github.com/nomiclabs/hardhat/issues/1139#issue-775939991

EDIT: copying over the bits relevant to `hardhat-deploy` :

Now the more serious bugs: 

- defaultNetwork: "ropsten" 
  - `npx hardhat node` 
  
![image](https://user-images.githubusercontent.com/36712489/103293223-bbb2ca00-49ef-11eb-827d-f3907609806b.png)

As you can see I am using `hardhat-deploy` which overrides the `hardhat node` task to run deploy scripts on start. I accidentally had my `defaultNetwork:` set to `ropsten` and somehow the `hardhat node` task did not fail and it deployed contracts to ropsten. 

**I would have expected `hardhat node` to fail with a Hardhat error similar to** `Error HH605: Unsupported network for JSON-RPC server.`

This works when `--network ropsten` is passed as a flag:

![image](https://user-images.githubusercontent.com/36712489/103293723-b3a75a00-49f0-11eb-8e3b-096810bee84c.png)

**But apparently not if the network is configured as defaultNetwork.**

**Either way the main issue:** 

When a `defaultNetwork` is configured **hardhat-deploy** seems to deploy all contracts to that network when invoking the `hardhat node` command in the terminal. Even worse, it bypassed all my deploy scripts skip functions for that `defaultNetwork`.

**Comment by gitpusha** [comment]
@alcuadrado confirmed  that this is how the vanilla `hardhat node` task evaluates the network / defaultNetwork config:

- `hardhat node` will always use "hardhat" network config and spin it up on localhost 

- if I pass a `--network <xyz>` flag and that network is not "hardhat", I should always get an error 

- `defaultNetwork` is completely disregarded by the `hardhat node` task - so it doesnt matter at all what's in there

**Comment by gitpusha** [comment]
One quick fix might be to change the default values of `hardhat-deploy` 's overriden `hardhat node` task: 

Default should be: `--no-deploy: true`

Or rather the flag should be replaced by: `--deploy` whose default should be set to `false`

**Comment by wighawag** [comment]
from what I see is that hardhat seem to allow running the node task on a separate network. not sure why
see here : https://github.com/nomiclabs/hardhat/blob/4f24717550f421f035380407f1c840ebaa8537ce/packages/hardhat-core/src/builtin-tasks/node.ts#L252-L259
and here : https://github.com/nomiclabs/hardhat/blob/4f24717550f421f035380407f1c840ebaa8537ce/packages/hardhat-core/src/builtin-tasks/node.ts#L82

I would like to understand the use case for it before blocking such use with hardhat-deploy

**Comment by wighawag** [comment]
Regarding `defaultNetwork is completely disregarded by the hardhat node task - so it doesnt matter at all what's in there`

How did you get your contract to be deployed on that network then ?

**Comment by wighawag** [comment]
Could it be that https://github.com/nomiclabs/hardhat/blob/4f24717550f421f035380407f1c840ebaa8537ce/packages/hardhat-core/src/builtin-tasks/node.ts#L82 does NOT actually set network.provider and so plugin that use network.provider will actually perform action on that network instead of the localhost node provider , @alcuadrado ?

**Comment by alcuadrado** [comment]
Yes, I think that's what's going on.

Why do we ignore the `defaultNetwork`? Because otherwise, if you use a `defaultNetwork`, you'd always have to run it with `--network hardhat`. I'm not sure if this was a good idea though.

**Comment by alcuadrado** [comment]
Maybe you can ensure in your override that it does get run with the `hardhat` network.

I'm a bit hesitant to do that change in hardhat core without properly investigating its impact.

**Comment by wighawag** [comment]
Yes I can do that, but the fact that network.provider is not set to be the actual provider used might cause issues in other plugin too

**Comment by gitpusha** [comment]
> Regarding `defaultNetwork is completely disregarded by the hardhat node task - so it doesnt matter at all what's in there`
> 
> How did you get your contract to be deployed on that network then ?

@wighawag I have no idea why it deployed and that's my question and issue. I certainly didnt expect it to deploy anything. I assume it has to do with the issues you (network.provider) you commented after the above quoted text.

**Comment by wighawag** [comment]
I added a check to ensure node only run on hardhat in 0.7.0-beta.40

**Comment by ccurves** [comment]
I'm currently experiencing this issue while trying to deploy to a forked mainnet network, @gitpusha you mentioned the issue was fixed over at the nomiclabs issue tab you opened. How did you rectify this?

**Comment by yohanelly95** [comment]
how do I run a different local chain using a new custom chainID and a different PORT. I want to run two different hardhat node networks. `npx hardhat node --network customChain` does not seem to work and throws `Unsupported network for JSON-RPC server. Only hardhat is currently supported.`

Can I use a custom local network while using hardhat-deploy? @wighawag

**Comment by wighawag** [comment]
@yohanelly95 the `node` command creates its own node

if you already have a node running, you do not need the `node` command

you can still use `deploy` or other command on that external node though

**Comment by yohanelly95** [comment]
I understand thank you! But in the case when I want to run two node instances, on different PORTS that can interact with each other ie, using the contracts written. So this was the command `npx hardhat node --network customChain` to get the second node up and running which is defined to use localhost but with a different port. @wighawag

**Comment by Winter9998** [comment]
Hello, Same problem happened to me yesterday  :
`Error in plugin hardhat-deploy: 
Unsupported network for JSON-RPC server. Only hardhat is currently supported.
hardhat-deploy cannot run on the hardhat provider when defaultNetwork is not hardhat, see https://github.com/nomiclabs/hardhat/issues/1139 and https://github.com/wighawag/hardhat-deploy/issues/63
you can specifiy hardhat via "--network hardhat" `

What I don't understand from this issue is why hasn't it been resolved since the first problem came in 2021 and we're in 2023 ? I still cannot run my scripts, because there is no Contract defined when starting running. 

`Error: No Contract deployed with name: SeamlessContract`

What is it that we can do if `--network hardhat` is not doing anything ? with or without

**Comment by wighawag** [comment]
Not sure what you are refering to @Winter9998 

As for @yohanelly95 sorry for the very late reply. If you want to run to `hardhat node on different` port, it should be possible as hardhat let you specify the port if I am correct. but that would be 2 separate network with their diffrent contract instance

**Comment by Winter9998** [comment]
@wighawag 

I am refering to the error I get from the hardhat-deploy plugin like I wrote above, I cannot deploy it on localhost when I try to run scripts. It was before possible to refer hardhat as defaultNetwork and still launch localhost, but now scripts cannot detect Contracts since It's on hardhat node and not the localhost one.  

> Error: No Contract deployed with name: SeamlessContract, 

> What is it that we can do if --network hardhat is not doing anything ? with or without

Refer to my previous message with quoted errors for more

**Comment by wighawag** [comment]
I still do not get why `Error: No Contract deployed with name: SeamlessContract,` is related to  ` What is it that we can do if --network hardhat is not doing anything ? with or without`

Can you please provide a reproduction repo
thanks

**Comment by Winter9998** [comment]
> I still do not get why `Error: No Contract deployed with name: SeamlessContract,` is related to ` What is it that we can do if --network hardhat is not doing anything ? with or without`
> 
> Can you please provide a reproduction repo thanks


All good it was a package problem that wouldn't let me use hardhat-deploy correctly. So I updated it and reinstalled the plugin

thanks for your help !

**Comment by AntonyC** [comment]
> All good it was a package problem that wouldn't let me use hardhat-deploy correctly. So I updated it and reinstalled the plugin thanks for your help !

@xyz899 Could you share more about how you fixed it? Which package was wrong, and how did you update it?
