### ISSUE TITLE
Proxy Deployment: need option to force skip Proxy redeployments 

### ISSUE THREAD

**Issue by gitpusha** [wighawag/hardhat-deploy#64]
I use proxy deployments and I recently changed my compiler version from `0.7.5` to `0.8.0`. 

I had an `EIP173ProxyWithReceive` in my project folder so `hardhat-deploy` used that one. I compiled that one with `0.7.5`. 

Now here is my issue: 

I want to compile all my contracts with `0.8.0` starting today. But if I change the EIP173ProxyWithReceive compiler pragma its bytecode might change too. I suspect that this will cause `hardhat-deploy` to deploy a new Proxy, even for existing deployments. However, I want existing deployments to keep and reuse their old Proxy deployment. 

So I guess I need some sort of option field to override this behaviour. Usually for normal contract deployments I use the `skip` function export to have control over the deployments the tool makes. However, with `proxy` deployments there is no `deploy` script that I am aware of. Probably there is a generic one shared by all contracts that use Proxies. So I guess the skip function cannot be replicated here. 

Maybe a field like `proxy.noRedeploy` might work, whose `default` value is `false`: 

```javascript
  await deploy("Foo", {
    from: deployer,
    proxy: {
      proxyContract: "EIP173ProxyWithReceive",
      noRedeploy: true
    },
```

I am sure there is a more succinct name instead of `noRedeploy`.

**Comment by wighawag** [comment]
the deployment through proxy should not redeploy the proxy even if the proxy bytecode changes.
proxy deployment, once deployed will only check if the implementation changes

**Comment by gitpusha** [comment]
Ok thanks, good to know. 

Sorry I prematurely / pre-emptively opened this issue because I didnt wanna risk having to pay for a costly mainnet redeployment with those crazy current gas prices.

Closing :)
