### ISSUE TITLE
Upgrading contracts controlled by multisig is a pain

### ISSUE THREAD

**Issue by blakewest** [wighawag/hardhat-deploy#70]
Hi, I'm working on upgrading a set of contracts previously deployed to mainnet and to rinkeby. But upgrading is controlled by a multisig. So whereas the first time, I could just deploy and got a nice deployments.json folder to use, I can't actually do that this time with hardhat-deploy, because I can't sign from the multisig within the scripts. 

Basically I'm wondering what's the best way to use hardhat-deploy for upgrading contracts when those contracts are controlled by a multisig which you can't programatically use.

Some ideas:
* Is there a way for me to get my deployments.json folder updated with the new ABI's and either generate what the new implementation address will be (given a multisig address), 
* Or, potentially generate a "staging" deployments.json where I can fill in the implementation addresses later?
* Wrap the functionality ideas above with a `--multisig {address}` flag. Meaning, when this flag is passed, it could skip trying to actually deploy, and instead just create a new staging deployments.json file, but with implementation addresses missing.

**Comment by wighawag** [comment]
@blakewest you can try 0.7.0-beta.45  which allow you to execute deploy after you made the deployment elsewhere and it will update the deployment files

Actually you can even do the following :

```
import {HardhatRuntimeEnvironment} from 'hardhat/types';
import {DeployFunction} from 'hardhat-deploy/types';

const func: DeployFunction = async function (hre: HardhatRuntimeEnvironment) {
  const {deployments, getNamedAccounts} = hre;
  const {deploy, catchUnknownSigner} = deployments;

  const {deployer, proxyOwner} = await getNamedAccounts();

  await catchUnknownSigner(
    deploy('Test', {
      from: deployer,
      log: true,
      proxy: {
        owner: proxyOwner,
      },
    })
  );
};
export default func;
```

when you run it first it will
- deploy 'Test_Implementation'
- deploy proxy (called 'Test') and set 'Test_Implementation' as implementation and 'proxyOwner' as owner

if you modify Test.sol and run it again, it will
- deploy a new version of 'Test_Implementation` (from = deployer)
- detect the proxy exist and attempt to perform an upgrade. it will stop right there though as proxyOwner is a multisig and the script does not have the capability to execute. The `catchUnknowSigner` ensure the call do not throw but instead output in the console the tx required to be made to perform the upgrade from `proxyOwner`


You can use this info to perform the upgrade (not that the new version of `test_Implementation` is already deployed

Once the upgrade is made, you can execute the script again. this time it will :
- see that `Test_Implementation` do not need to be redeployed
- see that the Proxy has its implementation changed and so will write the new details (including abi, etc...) in the deploymen/t file  `Test.json`

Let me know if you encounter any issue

**Comment by wighawag** [comment]
I ll close this but if the solution above does not work, please re-open

**Comment by jdbertron** [comment]
Then what ? I'd love to get this to work, I just need to know where you left it.
