### ISSUE TITLE
Diamonds not working as intended when manually deploying facets

### ISSUE THREAD

**Issue by lepidotteri** [wighawag/hardhat-deploy#72]
I noticed that this plugin, while offering [native support ](https://hardhat.org/plugins/hardhat-deploy.html#builtin-in-support-for-diamonds-eip2535) for Diamond Standard-compliant contracts, does not seem to allow for manual deployment and setup of the Diamond and its Facets. More precisely, with the following code: https://github.com/ARM-Finance/kingmaker/blob/1e7bb406e99108e8a87076d6fcc33d13be59df58/protocol/deploy/governance/02_kingmaker_governance_facet.ts#L16-L56 I will get the following error:
![image](https://user-images.githubusercontent.com/45174270/108198091-7c654780-711b-11eb-8bdf-9c85a3577e5f.png)

However, if I use the supported approach to deploying Diamonds with Faucets then the plugin is able to correctly interact with them with read() / execute() (e.g. https://github.com/ARM-Finance/kingmaker/blob/1e7bb406e99108e8a87076d6fcc33d13be59df58/protocol/deploy/01B_kingmaker_cowl.ts#L19). Can you point at this behavior in your code?

The rationale for my approach is the desire not to be bound to keep track of the existing facets and not to be forced to seemingly re-deploy a new Diamond with different facets, judging from the Diamantaire code and plugin API (e.g.
```
await diamond.deploy('ADiamondContract', {
    from: deployer,
    owner: diamondAdmin,
    facets: ['Facet1', 'Facet2', 'Facet3'],
  });

 await diamond.deploy('ADiamondContract', {
    from: diamondAdmin, // this need to be the diamondAdmin for upgrade
    owner: diamondAdmin,
    facets: ['NewFacet', 'Facet2', 'Facet3'],
 });
```

**Comment by wighawag** [comment]
Hey @lepidotteri note that the work on Diamond is still in beta and I did not have time to take care of it since some time. It is unlikely I ll have resources to look at it soon. I plan to remove it from the documentation in the mean time to avoid confusion.

Regarding your problem though, which implementation of Diamond are you using ?

**Comment by lepidotteri** [comment]
> Hey @lepidotteri note that the work on Diamond is still in beta and I did not have time to take care of it since some time. It is unlikely I ll have resources to look at it soon. I plan to remove it from the documentation in the mean time to avoid confusion.

Hi, thank you for the clarifications, your plugin is too valuable not to be relied upon, so if you agree I would just go ahead and fork it for our own organization, with the sole intent to update and better its current Diamond Standard support

> Regarding your problem though, which implementation of Diamond are you using ?
I am using the 3rd one here: https://github.com/mudgen/diamond-3. However, note that the implementation itself is not the issue, rather the problem is supposed to lie in the way your plugin interacts with the "custom" Diamonds that is not able to interface with correctly (e.g. https://github.com/ARM-Finance/kingmaker/blob/1e7bb406e99108e8a87076d6fcc33d13be59df58/protocol/deploy/governance/02_kingmaker_governance_facet.ts#L31 execute() fails here because, I suspect, the plugin uses the vanilla ethers.js to lookup the Facet method ABI, in this case 'diamondCut', against the "custom" Diamond ABI)

**Comment by lepidotteri** [comment]
So that's how you avoid ethers.js raising issues when performing checks on ABIs? https://github.com/wighawag/hardhat-deploy/blob/a842674b5a5a47ad2ee5b91c2fae1d3e1840e9b6/src/helpers.ts#L48

**Comment by wighawag** [comment]
@lepidotteri yes, so not sure why it does not work in your case, since as you see it include the diamondCutFact in the ABI

You should see it in the deployments/<network name>/Crow.json file


Regarding forking, it would be great if you make a PR. I would be happy to review it with the goal of being included back.
Thanks

**Comment by wighawag** [comment]
latest hardhat-deploy has revamped diamond support. reopen if there are any issue
