### ISSUE TITLE
Minor log/documentation corrections for the Sourcify task

### ISSUE THREAD

**Issue by FabijanC** [wighawag/hardhat-deploy#75]
- The error log of the Sourcify task refers to Etherscan instead of Sourcify: [line link](https://github.com/wighawag/hardhat-deploy/blob/master/src/sourcify.ts#L70).
- The text displayed with --help says that it uses sourcify.eth, but Sourcify does not use this: [line link](https://github.com/wighawag/hardhat-deploy/blob/master/src/index.ts#L637). The submit process itself is good as it uses sourcify.dev. This might have been caused by an issue in Sourcify itself, which has been [reported](https://github.com/ethereum/sourcify/issues/394).

**Comment by wighawag** [comment]
Thanks, fixed in 0.7.0-beta.46
