### ISSUE TITLE
Sourcify using network Mumbai (Matic testnet) 

### ISSUE THREAD

**Issue by dmcxx** [wighawag/hardhat-deploy#78]
Hey!
I'm running the following, to get the Contract verified, after deploying successfully the contract to the Mumbai network:
`npx hardhat sourcify --network mumbai`

However I get this output:
`verifying RandomNumberConsumer (0x7c90F0C9Eb46391c93d0545dDF4658d3B8DF1866 on chain 80001) .....           -
{"error":"Cannot read property 'contracts/RandomNumberConsumer.sol' of undefined"}`

[Link here - IPFS attach](https://cloudflare-ipfs.com/ipfs/QmY7bQE2ctHxqdUibQGr3ZiShfdPx8LbH4bsA57vygoWNT), what I got running it with the flag `--write-failing-metadata`

Contract address: 0x7c90F0C9Eb46391c93d0545dDF4658d3B8DF1866
Version: "hardhat-deploy": "^0.7.0-beta.46"

Let me know if any other information is needed to debug.

Thank you!

**Comment by FabijanC** [comment]
How was the linked file (metadata) generated?

**Comment by dmcxx** [comment]
> How was the linked file (metadata) generated?

It was generated when deploying using `hardhat --network mumbai deploy`

hardhat.config.js excert: 

    mumbai: {
      url: "https://rpc-mumbai.maticvigil.com/v1/key",
      accounts: [],
      chainId: 80001,
      gasPrice: 1000000000,
      live: true,
      saveDeployments: true,
      tags: ["staging"],
      gasMultiplier: 2
      }

**Comment by FabijanC** [comment]
@wighawag, the `libraries` property of the metadata file seems to cause recompilation issues. What is this `__CACHE_BREAKER__` that the `libraries` property specifies?

**Comment by FabijanC** [comment]
I tried removing `libraries` from the metadata file, and recompilation went just fine. However, matching could not be performed - it seems that the contract uses immutable state variables, and Sourcify currently cannot handle such contracts. So even after we settle this `libraries` issue, we won't be getting too happy because verification still won't be possible.

**Comment by wighawag** [comment]
@FabijanC `__CACHE_BREAKER__` is used by https://github.com/wighawag/hardhat-preprocessor/ to ensure the hardhat cache is not used when hardhat-preprocessor cannot be sure that the hardhat-preprocessor settings and input did not changed.

It basically generate a random address for that name so hardhat do not use the cache (which if it did it could miss the input/settings changes that should result in different pre-processing result)

I am happy to remove that from that tool and instead clear cache in all cases, if that cause problem, but I do not see why it should. ?

This is was exactly the input of solidity that generate such metadata after all.

Re immutable, I see, it is indeed already an issue recorded here : https://github.com/ethereum/sourcify/issues/194

**Comment by FabijanC** [comment]
Thanks for the info. You might not have to remove it. I've found the cause of the problem: the "libraries" format in metadata is not the same as in the standard-json format we use for recompilation. Thank you @dmcxx and @wighawag for reporting this.

**Comment by FabijanC** [comment]
Improved error reports will soon be available on the default Sourcify server. They are currently only available on the staging server, which can be accessed with the following command:
`npx hardhat sourcify --network mumbai --endpoint https://server.sourcify.shardlabs.io/`

However, your contract was written using immutable variables, which prevents it from being sourcified (the deployed bytecode is not the same as the recompiled bytecode). This case will soon be handled for some chains.

**Comment by fedealconada** [comment]
> @FabijanC `__CACHE_BREAKER__` is used by https://github.com/wighawag/hardhat-preprocessor/ to ensure the hardhat cache is not used when hardhat-preprocessor cannot be sure that the hardhat-preprocessor settings and input did not changed.
> 
> It basically generate a random address for that name so hardhat do not use the cache (which if it did it could miss the input/settings changes that should result in different pre-processing result)
> 
> I am happy to remove that from that tool and instead clear cache in all cases, if that cause problem, but I do not see why it should. ?
> 
> This is was exactly the input of solidity that generate such metadata after all.
> 
> Re immutable, I see, it is indeed already an issue recorded here : [ethereum/sourcify#194](https://github.com/ethereum/sourcify/issues/194)

The issue for me is that I'm getting a warning on Etherscan for that library
<img width="521" alt="image" src="https://user-images.githubusercontent.com/4473536/201083628-bd954f67-bfef-4f09-a836-c52e3028cb8c.png">

**Comment by wighawag** [comment]
I could add an option, this would be part of https://github.com/wighawag/hardhat-preprocessor though

But note that the reason this cache breaker exist is to ensure hardhat cache is not reused preventing your preprocessing to be screw up without you knowing.  This is an issue in hardhat, their caching check is applied to early, before the preprocessor can act

So if I add this option I would have to clear the cache to ensure you are not getting wrong result
