### ISSUE TITLE
Error: no signer for

### ISSUE THREAD

**Issue by stoplion** [wighawag/hardhat-deploy#79]
```
module.exports = async ({ ethers, getNamedAccounts, deployments }) => {
  const { deploy } = deployments;
  const { deployer } = await getNamedAccounts();

  log(`
    deployer: ${deployer} \n
    oracle address: ${process.env.ORACLE_ADDRESS} \n
  `);

  await deploy("ContractOne", {
    from: deployer,
    args: [process.env.ORACLE_ADDRESS],
  });
};

```

`Error: no signer for 0x16c8CF300eCE30f4d8e70201AB7163FCc3330f2d`

**Comment by wighawag** [comment]
Hi @stoplion thanks for the report
can I see the namedAccounts config in hardhat.config.js ?

**Comment by morrigan** [comment]
> Hi @stoplion thanks for the report
> can I see the namedAccounts config in hardhat.config.js ?

I can confirm the error. Worked a week ago but now with fresh `node_modules` getting these errors. I do use `yarn.lock` so not sure which lib is causing the issue.

**Comment by rokso** [comment]
@wighawag I am having similar issue. Here is namedAccount config
```js
  namedAccounts: {
    deployer: "0x16c8cF300Ece30f4d8e70201AB7163fCC3330f2d",
  },
```

**Comment by wighawag** [comment]
@rokso Where did you get the address from ?

You need to have the corresponding mnemonic or private key setup as part of the network's accounts field

**Comment by rokso** [comment]
@wighawag Address is not managed by node so I think adding mnemonic make sense.
