### ISSUE TITLE
Interesting ISSUE: produces different bytecode.

### ISSUE THREAD

**Issue by novaknole** [wighawag/hardhat-deploy#86]
I am also including the reproducible example.  here - https://github.com/novaknole/hardhat-bug/tree/second-bug (**NOTE**: branch is called : `second-bug` , not master.

* run `yarn` to install dependencies.
* go to `hardhat.config.ts` and replace `PUT HERE` by your private key of rinkeby.
* take a look at `./contracts` (T1, T2, Test2) contracts. They are super simple. `Test2` imports `T1, T2` and puts them in the constructor such as this:
```js
 constructor(T1 first, T2 second) public {
      
    }
```
*  There's a `deploy` folder which uses `deterministicDeployment:true`. 
* go to `./contracts/T1` and notice `uint x = 200` line. This is just a line that we will change to find the bug.

Okay.

* change `uint x = 200` to `uint x = 400`. and run `yarn deploy --network rinkeby`. T1, T2, Test2 will be deployed from scratch. if you run the command again, they won't be deployed again and console will say `reusing`. All good.
* change `uint x = 400` to `uint x = 600` and run `yarn deploy --network rinkeby`. T1, T2, Test2 will be deployed from scratch again. all good
* change `uint x = 600` back to what it was `uint x = 400`. Now, T1, T2 don't get deployed again. it says reusing, which seems correct. but `Test2` gets deployed again. 

How ? I changed my code exactly to what it wa s`uint x = 400`. So it shouldn't have deployed none of the contracts, but it still started to deploy `Test2`. what changed ? 

Hope you followed the explanation..

I'd appreciate the answer to this problem and a fix...

**Comment by wighawag** [comment]
HI @novaknole thanks for the report!
I just had a closer look and can see the issue, it seems the bug is that when a create2 deployments is found to already exist it does not update the deployment file fully if that one already exist

**Comment by wighawag** [comment]
fixed in "0.7.0-beta.49"
