### ISSUE TITLE
How to have an upgradable contract that extends OZ/Ownable?

### ISSUE THREAD

**Issue by marcelomorgado** [wighawag/hardhat-deploy#87]
Hi,

I'm trying the upgrade feature but facing issues because my implementation contracts (that extend `Ownable`) are conflicting with the `EIP173Proxy` that also has the `owner()` function.
Plus, when extending the `Proxied` contract, it's also conflicting with the `Ownable`.
As a workaround, I've removed the `Ownable` inheritance and left `Proxied` instead.
The setup is working but I haven't the ownable features anymore.
Am I missing something?

I'm wondering if wouldn't be better to have `proxyAdmin` instead of `owner` for Proxy contracts since `Ownable` is a well-used contract.

**Comment by wighawag** [comment]
Hi @marcelomorgado thanks for the feedback
I guess it depends on use case, I personally like that my proxy are EIP173 compatible but I can also see the benefit in not having them that way. It should be easy to make a non-EIP173 compatible one and I ll do a version soon

If you cannot wait you should be able to provide your own version right now via :

```
deploy("MyContract", {from: deployer, proxy: {contract: "<proxy contract artifactName>"}});
```

the only requirement are that it has a `function changeImplementation(address newImplementation, bytes calldata data) external payable;` function like ERIP173Proxy and that the `admin` is stored on slot `0xb53127684a568b3173ae13b9f8a6016e243e63b6e8ee1178d6a717850b5d6103`

Let me know if you encounter issues with that.



By the way I am also working on making it possible to use openzeppelin Transparent Proxy in the  the [openzeppelin-transparent-proxy branch](https://github.com/wighawag/hardhat-deploy/tree/openzeppelin-transparent-proxy) which should also help you.

**Comment by marcelomorgado** [comment]
Hi, I've tried that but I've faced some issues, I've ended by adopting the solution from https://github.com/wighawag/hardhat-deploy/issues/82#issuecomment-800706046 it's working pretty fine.

**Comment by wighawag** [comment]
Hey @marcelomorgado new version of hardhat-deploy support openzeppelin contract out of the box.

```ts
deploy("MyContract", {from: deployer, proxy: {proxyContract: "OpenZeppelinTransparentProxy"}});
```

**Comment by wighawag** [comment]
Closing this as this is achievable using transparent proxy
