### ISSUE TITLE
How to use create2 to predermine contract address

### ISSUE THREAD

**Issue by rubydog** [wighawag/hardhat-deploy#92]
Hi there,

I am trying to predetermine address for my contract before deployment because of some circular dependencies I have.

I have two contracts A and B, contract A needs B's address as constructor argument, and Contract B needs A's address as constructor argument. How can I deploy such circular dependent contracts?

Thanks in advance for help!

**Comment by wighawag** [comment]
Hi @rubydog 

you can use the hre.deployments.deterministic function like that :

```
const {address, deploy} = await deterministic('<deploymentName>', {
    from: deployer,
    args: [...],
    log: true,
  });
  const deployment = await deploy();
```

it basically return a promise to an object with an address field and a deploy function

I found out that this does not work with proxy options, need to fix that, as currently if you use it with proxy: true it return the address of the implementation contract, not that of the proxy

but if you are not using proxy: true, the address field will be the expected one

**Comment by rubydog** [comment]
@wighawag thanks for the prompt reply.

I tried `deterministic` function. Say I have two contracts like below:

```
contract Foo {
    constructor(address _bar) {
        bar = Bar(_b);
    }
}

contract Bar {
    constructor(address _foo) {
        foo = Foo(_foo);
    }
}
```

and deploy script like below:
```
const {addressFoo, deployFoo} = await deterministic('Foo', {
    from: deployer,
    args: ['someRandomAddress'],
    log: true,
});

const bar = await deploy('Bar', {
    from: deployer,
    args: [addressFoo],
    log: true
});
```

Now when I deploy foo with `const deployment = await deployFoo()`. Bar's address in foo is `someRandomAddress` passed in argument above. But instead I would want to replace that with deployed `bar.address`. How can I achieve this?

**Comment by wighawag** [comment]
ha ok, this is not actually possible since the create2 address is based on the tx data (this include constructor param)

You could create them through another contract though. if that intermediary contract is deployed deterministicly then you can also compute what will be the address of the other 2.

**Comment by rubydog** [comment]
@wighawag thanks for the prompt reply again.

Is there a way to get future account address with hardhat-deploy by increasing nonce?

**Comment by rubydog** [comment]
For future reference, If anybody is looking to calculate future addresses. Here is a way to do it

```
const nonce = await web3.eth.getTransactionCount(deployer)
const futureAddress = ethers.utils.getContractAddress({ from: deployer, nonce: nonce+1 });
```
