### ISSUE TITLE
hh node default to localhost instead of hardhat

### ISSUE THREAD

**Issue by PatrickAlphaC** [wighawag/hardhat-deploy#95]
When you run `hh node`, it defaults to `localhost`, you can even check the tooltip

```
h node --help
Hardhat version 2.1.2

Usage: hardhat [GLOBAL OPTIONS] node --as-network <STRING> --export <STRING> --export-all <STRING> --fork <STRING> --fork-block-number <INT> [--fork-deployments <STRING>] --gasprice <STRING> --hostname <STRING> [--no-deploy] [--no-impersonation] [--no-reset] [--port <INT>] [--show-accounts] [--silent] --tags <STRING> [--watch] [--write <BOOLEAN>]

OPTIONS:

  --as-network          network name to be used, default to "localhost" (or to `--fork-deployments` value) 
```

However, when running `hh node` and having the `hardhat.config.js` defaulting to `localhost`, you get this error:

```
Error in plugin hardhat-deploy: 
Unsupported network for JSON-RPC server. Only hardhat is currently supported.
hardhat-deploy cannot run on the hardhat provider when defaultNetwork is not hardhat, see https://github.com/nomiclabs/hardhat/issues/1139 and https://github.com/wighawag/hardhat-deploy/issues/63
you can specifiy hardhat via "--network hardhat"
```

This is both confusing, and frustrating.

**Comment by wighawag** [comment]
The issues mentioned in the error explain why this is currently the case.

hardhat node always run on hardhat network but to then operate on it, you ll need to use `--network localhost`  as this is now a running network. This is indeed confusing but this is simply how it works with hardhat currently. 

To make things simpler, hardhat-deploy use the string `localhost` for its internal saving mechanism. This is allow you to get access to the deployment when running as node.


I am not sure I answered your question though. What is the problem you are tying to solve ?

**Comment by PatrickAlphaC** [comment]
No you did, basically the answer is "that's just how it is"

I'd imagine there is a better way to show this as it's a bit confusing. But if that's just the way it is for now, so be it.
