### ISSUE TITLE
Convert ethersproject dependencies to peer dependencies

### ISSUE THREAD

**Issue by rmeissner** [wighawag/hardhat-deploy#97]
Currently you might run into issues when using the latest ethers version with the latest hardhat-deploy version as they have slightly different bignumber implementations. it would be nice if these dependencies could be marked as peer dependencies so that the version of the project that makes use of this plugin is used.

**Comment by wighawag** [comment]
Hi @rmeissner thanks for the report.

Could you explain the issue with the different bignumber version ? I expect the bignumber version to be compatible, no ?

I am open to make @ethersproject lib peer dependencies but that is not ideal as this qill require users to install it while hardhat-deploy is agnostic to the library used by the end-user. So with peer dependencies, even a web3.js users would have to install the @ethersproject dependencies.

**Comment by rmeissner** [comment]
Hey, 
I was updating to ethers 5.1.0 (to have support for the transaction types). And when I imported `BigNumber` from ethers and check it with chai against a value queried from the contract it fails telling me the values are different (as hardhat deploy is using version 5.0.x). I am using `deep` to compare them and this worked quite well until now, but with the differences in version it fails (weirdly enough only in some cases not in all). A solution is to use `toNumber` or to force the resolution of the ethersproject depedencies to the same version.

An example of a check can be found here: https://github.com/gnosis/safe-contracts/blob/development/test/core/GnosisSafe.GuardManager.spec.ts#L70

I do get your point with the web3.js user, but right now isn't that what is happening anyways? Just by installing this dependencies you will see all the ethersproject packages popping up in your lock file. Also afaik peer dependencies are optional, e.g. I don't have to install them (I can just ignore the warning). 

But yeah, the issue is not super critical. More a nice to have if it is somehow easily done. 

Note: I reverted back to ethers 5.0.x as the transaction types where more for a prototype and are not required in this project.

**Comment by wighawag** [comment]
I see, to me the issue is the use of `deep` as this make your test brittle if you ever update your big number version, maybe because some of your other dependency require a higher one for whatever reason. making hardhat-deploy use peer dependencies would not help in that case.

instead of deep equal you can use chai ​matchers like https://www.npmjs.com/package/@ethereum-waffle/chai or (my fork of it to make it dependent on less stuff: https://www.npmjs.com/package/chai-ethers)


>   but right now isn't that what is happening anyways? Just by installing this dependencies you will see all the ethersproject packages popping up in your lock file. Also afaik peer dependencies are optional, e.g. I don't have to install them (I can just ignore the warning).

They will show up in the lock file yes but the issue is that if the user does not install them, it would not work, as hardhat-deploy requires them to function. so as a web3.js user I would need to make sure ethers dependencies are also installed.

**Comment by rmeissner** [comment]
Hmm I am using `chai` already. But if I use just `eq` it doesn't like it for 2 big numbers.

For me the major issue was that I wanted to update what ethers version is used by the library. Was hoping that there is an easy way to automatically use the same version as the project that includes this (might be related to a minor version update vs a bugfix update). 

If not feasible feel free to close it.

**Comment by wighawag** [comment]
I agree, I wish there was something like peerDependency but that 
- install it if not required by other
- match the version of the one installed if any

I ll leave it open as there might be a solution. I ll close if I cannot find any. thanks again for the feedback

re `eq` that's weird. I use `equals` and did not have issues with 2 BigNmber equality (as far as I remember) but this would be weird if it matters.
